import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const output = resolve(root, "navigation/maps/demo_3d/source/map_nav.obj");
const vertices = [];
const faces = [];

function addQuad(a, b, c, d) {
  const start = vertices.length + 1;
  vertices.push(a, b, c, d);
  faces.push([start, start + 1, start + 2], [start, start + 2, start + 3]);
}

function addBox(minX, minY, minZ, maxX, maxY, maxZ) {
  addQuad([minX, maxY, minZ], [minX, maxY, maxZ], [maxX, maxY, maxZ], [maxX, maxY, minZ]);
  addQuad([minX, minY, maxZ], [minX, minY, minZ], [maxX, minY, minZ], [maxX, minY, maxZ]);
  addQuad([minX, minY, minZ], [minX, maxY, minZ], [maxX, maxY, minZ], [maxX, minY, minZ]);
  addQuad([maxX, minY, maxZ], [maxX, maxY, maxZ], [minX, maxY, maxZ], [minX, minY, maxZ]);
  addQuad([minX, minY, maxZ], [minX, maxY, maxZ], [minX, maxY, minZ], [minX, minY, minZ]);
  addQuad([maxX, minY, minZ], [maxX, maxY, minZ], [maxX, maxY, maxZ], [maxX, minY, maxZ]);
}

// 固定灰盒不是展示地图；它刻意包含开阔地、不可攀爬障碍和多Tile边界，供工具链确定性回归。
// This deterministic graybox is not visual content; it exercises open ground, an unclimbable obstacle, and tile seams.
addQuad([-24, 0, -24], [-24, 0, 24], [24, 0, 24], [24, 0, -24]);
addBox(-3, 0, -5, 3, 3, 5);

const lines = [
  "# Generated by tools/navigation/generate_graybox.mjs. Do not edit.",
  "o TiangZ_Phase_4_2_Graybox",
  ...vertices.map(([x, y, z]) => `v ${x} ${y} ${z}`),
  ...faces.map((face) => `f ${face.join(" ")}`),
  "",
];
await mkdir(dirname(output), { recursive: true });
await writeFile(output, lines.join("\n"), "utf8");
console.log(`[navigation] generated ${output}`);
