class_name TiangZClient
extends Node

## Godot WebSocket SDK适配；连接流程手写，协议Codec由主工程自动生成。
## Godot WebSocket SDK adapter; flow is handwritten, while protocol codecs are generated by the main project.

signal status_changed(text: String, is_error: bool)
signal map_entered(snapshot: Dictionary)
signal map_ready(snapshot: Dictionary)
signal navigate_push(message: Dictionary)
signal aoi_delta(message: Dictionary)
signal entity_enter(entity: Dictionary)
signal entity_leave(unit_id: int)
signal door_changed(closed: bool, changed: bool)
signal ping_result(latency_ms: int, server_time_ms: int)

var peer: WebSocketPeer
var account: String
var phase := "idle"
var rpc_id := 1
var pending: Dictionary = {}
var connect_callback: Callable
var socket_opened := false
var last_ping_ms := 0
var ping_sent_at := 0
var token := ""
var door_request_pending := false

func start(in_account: String, login_mgr_host := "127.0.0.1", login_mgr_port := 7000) -> void:
	account = in_account
	_emit_status("正在连接 LoginMgr %s:%d" % [login_mgr_host, login_mgr_port], false)
	_connect(login_mgr_host, login_mgr_port, Callable(self, "_request_login_service_addr"))

func _process(_delta: float) -> void:
	if peer == null:
		return
	peer.poll()
	var state := peer.get_ready_state()
	if state == WebSocketPeer.STATE_OPEN and not socket_opened:
		socket_opened = true
		if connect_callback.is_valid():
			var callback := connect_callback
			connect_callback = Callable()
			callback.call()
	elif state == WebSocketPeer.STATE_CLOSED:
		if phase != "closed":
			_emit_status("WebSocket已关闭", true)
			phase = "closed"
			peer = null
			pending.clear()

	while peer != null and peer.get_available_packet_count() > 0:
		_handle_packet(peer.get_packet())

	if phase == "map" and Time.get_ticks_msec() - last_ping_ms >= 5000 and not _has_pending_response(TiangZProto.G2C_PING):
		last_ping_ms = Time.get_ticks_msec()
		ping_sent_at = last_ping_ms
		_send_rpc(TiangZProto.C2G_PING, TiangZProto.encode_c2g_ping({}), TiangZProto.G2C_PING, Callable(self, "_on_ping"))

func navigate_to(x: float, y: float, z: float, sequence: int) -> bool:
	if phase != "map":
		return false
	_send_rpc(TiangZProto.C2M_NAVIGATE_TO, TiangZProto.encode_c2m_navigate_to({
		"target_x": x,
		"target_y": y,
		"target_z": z,
		"sequence": sequence,
	}), TiangZProto.M2C_NAVIGATE_TO, Callable(self, "_on_navigate_response"))
	return true

func navigate_input(forward: int, strafe: int, yaw: float, sequence: int) -> bool:
	if phase != "map":
		return false
	_send_rpc(TiangZProto.C2M_NAVIGATE_INPUT, TiangZProto.encode_c2m_navigate_input({
		"forward": forward,
		"strafe": strafe,
		"yaw": yaw,
		"sequence": sequence,
	}), TiangZProto.M2C_NAVIGATE_INPUT, Callable(self, "_on_navigate_response"))
	return true

func toggle_demo_door(closed: bool) -> bool:
	if phase != "map" or door_request_pending:
		return false
	door_request_pending = true
	_send_rpc(TiangZProto.C2M_TOGGLE_DEMO_DOOR, TiangZProto.encode_c2m_toggle_demo_door({"closed": closed}), TiangZProto.M2C_TOGGLE_DEMO_DOOR, Callable(self, "_on_door_response"))
	return true

func _connect(host: String, port: int, callback: Callable) -> void:
	if peer != null:
		peer.close()
	peer = null
	pending.clear()
	socket_opened = false
	connect_callback = callback
	peer = WebSocketPeer.new()
	var error := peer.connect_to_url("ws://%s:%d" % [host, port])
	if error != OK:
		_emit_status("连接失败：%s" % error_string(error), true)
		phase = "closed"

func _request_login_service_addr() -> void:
	phase = "login_mgr"
	_send_rpc(TiangZProto.C2S_GET_LOGIN_SERVICE_ADDR, TiangZProto.encode_c2s_get_login_service_addr({}), TiangZProto.S2C_GET_LOGIN_SERVICE_ADDR, Callable(self, "_on_login_service_addr"))

func _on_login_service_addr(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var body := TiangZProto.decode_s2c_get_login_service_addr(response.payload)
	_emit_status("LoginMgr已选择 %s:%d" % [body.ip, body.port], false)
	_connect(body.ip, body.port, Callable(self, "_request_login"))

func _request_login() -> void:
	phase = "login"
	_send_rpc(TiangZProto.C2S_LOGIN, TiangZProto.encode_c2s_login({"account": account}), TiangZProto.S2C_LOGIN, Callable(self, "_on_login"))

func _request_login_gate() -> void:
	phase = "gate_login"
	_send_rpc(TiangZProto.C2G_LOGIN_GATE, TiangZProto.encode_c2g_login_gate({"account": account, "token": token}), TiangZProto.G2C_LOGIN_GATE, Callable(self, "_on_login_gate"))

func _on_login(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var body := TiangZProto.decode_s2c_login(response.payload)
	token = body.token
	_emit_status("登录成功，正在连接 Gate %s:%d" % [body.gate_ip, body.gate_port], false)
	_connect(body.gate_ip, body.gate_port, Callable(self, "_request_login_gate"))

func _on_login_gate(response: Dictionary) -> void:
	if not _check_response(response):
		return
	phase = "enter_map"
	_send_rpc(TiangZProto.C2G_ENTER_MAP, TiangZProto.encode_c2g_enter_map({"map_id": 100, "map_instance_id": 0}), TiangZProto.G2C_ENTER_MAP, Callable(self, "_on_enter_map"))

func _on_enter_map(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var snapshot := TiangZProto.decode_g2c_enter_map(response.payload)
	phase = "map"
	last_ping_ms = Time.get_ticks_msec()
	map_entered.emit(snapshot)
	_emit_status("已进入 Map %d，Unit %d" % [snapshot.map_id, snapshot.unit_id], false)
	_send_rpc(TiangZProto.C2G_MAP_SNAPSHOT_READY, TiangZProto.encode_c2g_map_snapshot_ready({"unit_id": snapshot.unit_id}), TiangZProto.G2C_MAP_SNAPSHOT_READY, Callable(self, "_on_snapshot_ready"))

func _on_snapshot_ready(response: Dictionary) -> void:
	if _check_response(response):
		var state := TiangZProto.decode_g2c_map_snapshot_ready(response.payload)
		door_changed.emit(state.demo_door_closed, false)
		_emit_status("地图快照监听已就绪", false)

func _on_navigate_response(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_navigate_to(response.payload)
	if result.error != 0:
		_emit_status("导航请求失败：%s" % result.message, true)

func _on_door_response(response: Dictionary) -> void:
	door_request_pending = false
	if not _check_response(response):
		return
	var result := TiangZProto.decode_m2c_toggle_demo_door(response.payload)
	door_changed.emit(result.closed, result.changed)

func _on_ping(response: Dictionary) -> void:
	if not _check_response(response):
		return
	var result := TiangZProto.decode_g2c_ping(response.payload)
	var now := Time.get_ticks_msec()
	ping_result.emit(now - ping_sent_at, result.server_time)

func _send_rpc(msg_code: int, payload: PackedByteArray, response_code: int, callback: Callable) -> void:
	if peer == null or peer.get_ready_state() != WebSocketPeer.STATE_OPEN:
		return
	var current_id := rpc_id
	rpc_id += 1
	var body := TiangZProto.with_rpc(current_id, payload)
	pending[current_id] = {"expected": response_code, "callback": callback, "payload": PackedByteArray()}
	peer.send(TiangZProto.frame(msg_code, body), WebSocketPeer.WRITE_MODE_BINARY)

func _handle_packet(packet: PackedByteArray) -> void:
	if packet.size() < 2:
		_emit_status("收到损坏的Godot协议包", true)
		return
	var msg_code := (int(packet[0]) << 8) | int(packet[1])
	var payload := packet.slice(2)
	if msg_code == TiangZProto.G2C_MAP_READY:
		map_ready.emit(TiangZProto.decode_g2c_map_ready(payload))
	elif msg_code == TiangZProto.G2C_ENTITY_NAVIGATE:
		navigate_push.emit(TiangZProto.decode_g2c_entity_navigate(payload))
	elif msg_code == TiangZProto.G2C_AOI_DELTA:
		aoi_delta.emit(TiangZProto.decode_g2c_aoi_delta(payload))
	elif msg_code == TiangZProto.G2C_ENTITY_ENTER:
		entity_enter.emit(TiangZProto.decode_g2c_entity_enter(payload).entity)
	elif msg_code == TiangZProto.G2C_ENTITY_LEAVE:
		entity_leave.emit(TiangZProto.decode_g2c_entity_leave(payload).unit_id)
	elif msg_code == TiangZProto.G2C_DEMO_DOOR_STATE:
		door_changed.emit(TiangZProto.decode_g2c_demo_door_state(payload).closed, true)
	else:
		var response_id := TiangZProto.decode_rpc_id(payload)
		if pending.has(response_id):
			var request: Dictionary = pending[response_id]
			pending.erase(response_id)
			if request.expected != msg_code:
				_emit_status("RPC响应不匹配：%d != %d" % [msg_code, request.expected], true)
				return
			var callback: Callable = request.callback
			var response := {"rpc_id": response_id, "payload": payload, "error": 0, "message": ""}
			var meta := TiangZProto.decode_error(payload)
			response.error = meta.error
			response.message = meta.message
			callback.call(response)

func _check_response(response: Dictionary) -> bool:
	if int(response.error) != 0:
		_emit_status("请求失败：%s" % response.message, true)
		return false
	return true

func _has_pending_response(response_code: int) -> bool:
	for request in pending.values():
		if request.expected == response_code:
			return true
	return false

func _emit_status(text: String, is_error: bool) -> void:
	status_changed.emit(text, is_error)
