syntax = "proto3";

package ets.demo;

message LoginServiceAddress
{
  string name = 1;
  string ip = 2;
  uint32 port = 3;
}

message MapEntitySnapshot
{
  uint32 unit_id = 1;
  sint32 x = 2;
  sint32 y = 3;
  float heading = 4;
  bool alive = 5;
  bytes state = 6;
  string account = 7;
  sint32 cell_x = 8;
  sint32 cell_y = 9;
  repeated UnitNumericDelta numerics = 10;
  float speed_cells_per_second = 11;
}

message CellMovementState
{
  uint32 unit_id = 1;
  uint32 acknowledged_sequence = 2;
  sint32 from_cell_x = 3;
  sint32 from_cell_y = 4;
  sint32 to_cell_x = 5;
  sint32 to_cell_y = 6;
  uint32 move_start_tick = 7;
  uint32 move_end_tick = 8;
  bool moving = 9;
}

message UnitNumericDelta
{
  uint32 unit_id = 1;
  uint32 numeric_type = 2;
  sint32 value = 3;
}

message UnitStateDelta
{
  uint32 unit_id = 1;
  uint32 dirty_mask_low = 2;
  uint32 dirty_mask_high = 3;
  float x = 4;
  float y = 5;
  float speed_cells_per_second = 6;
  bool alive = 7;
}

message ItemSnapshot
{
  uint32 item_id = 1;
  uint32 config_id = 2;
  uint32 count = 3;
  uint32 quality = 4;
  uint32 level = 5;
  uint32 version = 6;
}
