import { createHash } from "node:crypto";
import { lstat, mkdir, readFile, readdir, realpath, unlink, writeFile } from "node:fs/promises";
import path from "node:path";

const languages = {
  typescript: { source: "client_sdk/typescript", extension: ".ts", exclude: "Generated/Model/bench/" },
  cpp: { source: "client_sdk/cpp/include", extension: ".h" },
  csharp: { source: "client_sdk/csharp", extension: ".cs" },
  godot: { source: "client_sdk/godot/generated", extension: ".gd" },
};

/** 只同步项目显式声明的生成物；保留编辑器元数据，拒绝覆盖被手改的已发布文件。
 * Publishes explicitly declared generated assets, preserving editor metadata and protecting edited outputs.
 */
export async function publishClientSdk({ engineRoot, projectRoot, check = false }) {
  engineRoot = await realpath(engineRoot);
  projectRoot = await realpath(projectRoot);
  const config = JSON.parse(await readFile(path.join(projectRoot, "tiangz.clients.json"), "utf8"));
  if (config.formatVersion !== 1 || !Array.isArray(config.sdkTargets) || !Array.isArray(config.handlerTargets)) {
    throw new Error("tiangz.clients.json requires formatVersion=1, sdkTargets and handlerTargets");
  }
  const outputs = new Map();
  const scopes = [];
  const reserve = (file, directory) => {
    const key = process.platform === "win32" ? file.toLowerCase() : file;
    for (const scope of scopes) {
      if (key === scope.key || key.startsWith(scope.key + path.sep) || scope.key.startsWith(key + path.sep)) {
        throw new Error(`overlapping generated targets: ${file}`);
      }
    }
    scopes.push({ key, directory });
  };
  const add = (file, content) => {
    if (outputs.has(file)) throw new Error(`duplicate generated output: ${file}`);
    outputs.set(file, content);
  };
  for (const target of config.sdkTargets) {
    const language = languages[target.language];
    if (!language) throw new Error(`unknown SDK language: ${target.language}`);
    const destination = await contained(projectRoot, target.output);
    reserve(destination, true);
    const source = target.source === undefined ? path.join(engineRoot, language.source) : await contained(projectRoot, target.source);
    if (source === destination || destination.startsWith(source + path.sep) || source.startsWith(destination + path.sep)) throw new Error("client SDK source and output must not overlap");
    const before = outputs.size;
    for (const file of await collect(source)) {
      const relative = path.relative(source, file).replaceAll(path.sep, "/");
      if (!file.endsWith(language.extension) || (language.exclude && relative.startsWith(language.exclude))) continue;
      add(path.join(destination, relative), await readFile(file));
    }
    if (outputs.size === before) throw new Error(`canonical SDK is empty: ${target.language}`);
  }
  for (const target of config.handlerTargets) {
    const output = await contained(projectRoot, target.output);
    if (!output.endsWith(".ts")) throw new Error("handler output must be a TypeScript file");
    reserve(output, false);
    const source = await contained(projectRoot, target.source);
    const files = (await collect(source)).filter((file) => file.endsWith("Handler.ts") &&
      path.relative(source, file).split(path.sep).some((part) => part.toLowerCase() === "handlers"));
    const imports = files.sort().map((file) => {
      const relative = path.relative(path.dirname(output), file).replaceAll(path.sep, "/").replace(/\.ts$/, "");
      return `import ${JSON.stringify(relative.startsWith(".") ? relative : `./${relative}`)};`;
    });
    add(output, Buffer.from(["// Generated by tools/publish_client_sdk.mjs. Do not edit by hand.", ...imports, ""].join("\n")));
  }
  if (!outputs.size) throw new Error("client publishing plan is empty");
  const manifestFile = await contained(projectRoot, ".tiangz/client-sdk.manifest.json");
  reserve(manifestFile, false);
  let previous;
  try { previous = JSON.parse(await readFile(manifestFile, "utf8")); }
  catch (error) { if (error.code !== "ENOENT") throw error; }
  if (previous && (previous.formatVersion !== 1 || !previous.files || typeof previous.files !== "object" || Array.isArray(previous.files))) {
    throw new Error("invalid client SDK manifest");
  }
  const stale = [];
  const changes = [];
  // 先验证全部路径和旧哈希，再写入任何文件；失败不会造成半次迁移。
  // Validate all paths and prior hashes before writing, so preflight failures leave outputs untouched.
  for (const [relative, hash] of Object.entries(previous?.files ?? {})) {
    const file = await contained(projectRoot, relative);
    const key = process.platform === "win32" ? file.toLowerCase() : file;
    if (!scopes.some((scope) => scope.directory ? key.startsWith(scope.key + path.sep) : key === scope.key)) {
      throw new Error(`previous output is no longer declared; preserve it before changing targets: ${relative}`);
    }
    const current = await optionalRead(file);
    if (current && digest(current) !== hash && (!outputs.has(file) || digest(current) !== digest(outputs.get(file)))) {
      throw new Error(`generated client file was edited; preserve or revert it before publishing: ${relative}`);
    }
    if (!outputs.has(file) && current) stale.push(file);
  }
  for (const [file, content] of outputs) {
    await contained(projectRoot, path.relative(projectRoot, file));
    const current = await optionalRead(file);
    if (!current || digest(current) !== digest(content)) changes.push([file, content]);
  }
  const files = Object.fromEntries([...outputs].sort(([a], [b]) => a.localeCompare(b, "en"))
    .map(([file, content]) => [path.relative(projectRoot, file).replaceAll(path.sep, "/"), digest(content)]));
  const manifest = JSON.stringify({ formatVersion: 1, files }, null, 2) + "\n";
  const manifestChanged = (await optionalRead(manifestFile))?.toString("utf8") !== manifest;
  if (check) {
    if (changes.length || stale.length || manifestChanged) throw new Error(`client SDK is stale: ${changes.length} changed, ${stale.length} obsolete; run sdk:sync`);
  } else {
    for (const [file, content] of changes) { await mkdir(path.dirname(file), { recursive: true }); await writeFile(file, content); }
    for (const file of stale) await unlink(file);
    await mkdir(path.dirname(manifestFile), { recursive: true });
    await writeFile(manifestFile, manifest);
  }
  return { files: outputs.size, changed: changes.length, removed: stale.length, check };
}

/** 校验每一层，禁止生成路径通过目录联接逃出项目。
 * Checks every component to prevent junctions or symlinks from redirecting generated writes.
 */
async function contained(root, relative) {
  if (typeof relative !== "string" || !relative || path.isAbsolute(relative)) throw new Error(`expected project-relative output: ${relative}`);
  const file = path.resolve(root, relative);
  const resolved = path.relative(root, file);
  if (!resolved || resolved.startsWith("..") || path.isAbsolute(resolved)) throw new Error(`path escapes client project: ${relative}`);
  let cursor = root;
  for (const part of resolved.split(path.sep)) {
    cursor = path.join(cursor, part);
    try { if ((await lstat(cursor)).isSymbolicLink()) throw new Error(`client output links are forbidden: ${relative}`); }
    catch (error) { if (error.code !== "ENOENT") throw error; }
  }
  return file;
}

async function collect(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) throw new Error(`client source links are forbidden: ${path.join(directory, entry.name)}`);
    if (["node_modules", "library", "temp", "bin", "obj", ".git"].includes(entry.name)) continue;
    const file = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collect(file));
    else if (entry.isFile()) files.push(file);
  }
  return files.sort();
}

async function optionalRead(file) {
  try { return await readFile(file); } catch (error) { if (error.code === "ENOENT") return undefined; throw error; }
}

function digest(bytes) { return createHash("sha256").update(bytes.toString("utf8").replaceAll("\r\n", "\n")).digest("hex"); }
