import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const config = JSON.parse(
  await readFile(path.join(root, "codegen.config.json"), "utf8"),
);
const clientConfig = config.clientHotfix;
if (!clientConfig?.enabled) process.exit(0);

const outputFile = path.resolve(root, clientConfig.handlerOutput);
const searchRoots = clientConfig.handlerSearchRoots.map((item) =>
  path.resolve(root, item)
);
const handlerFiles = [];
for (const searchRoot of searchRoots) {
  await collectHandlerFiles(searchRoot, handlerFiles);
}
handlerFiles.sort((left, right) => left.localeCompare(right, "en"));

const imports = handlerFiles.map((file) => {
  const relative = path
    .relative(path.dirname(outputFile), file)
    .replace(/\.ts$/, "")
    .replaceAll(path.sep, "/");
  return `import "${relative.startsWith(".") ? relative : `./${relative}`}";`;
});
const content = [
  "// Generated by tools/codegen_client_handlers.mjs. Do not edit by hand.",
  ...imports,
  "",
].join("\n");

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, content, "utf8");
console.log(`[codegen:client-handlers] generated ${handlerFiles.length} import(s)`);

async function collectHandlerFiles(directory, files) {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return;
    throw error;
  }
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (["Generated", "node_modules", "temp", "library"].includes(entry.name)) {
        continue;
      }
      await collectHandlerFiles(fullPath, files);
      continue;
    }
    const segments = path.normalize(fullPath).split(path.sep);
    if (
      entry.isFile() &&
      entry.name.endsWith("Handler.ts") &&
      segments.some((segment) => segment.toLowerCase() === "handlers")
    ) {
      files.push(fullPath);
    }
  }
}
