import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaFile = path.join(root, "native_data", "demo", "Unit.native");
const rustOutput = path.join(root, "src", "generated", "native_data.rs");
const tsOutput = path.join(
  root,
  "app",
  "generated",
  "model",
  "native",
  "NativeUnitRef.ts",
);

const schema = parseSchema(await readFile(schemaFile, "utf8"));
validateUnitSchema(schema);
await mkdir(path.dirname(rustOutput), { recursive: true });
await mkdir(path.dirname(tsOutput), { recursive: true });
await writeFile(rustOutput, renderRust(schema), "utf8");
await writeFile(tsOutput, renderTypeScript(), "utf8");
console.log(
  `[codegen:native-data] generated ${path.relative(root, rustOutput)} and ${path.relative(root, tsOutput)}`,
);

function parseSchema(source) {
  const clean = source.replace(/\/\/.*$/gm, "");
  const namespace = /\bnamespace\s+([A-Za-z_]\w*)\s*;/.exec(clean)?.[1];
  if (!namespace) throw new Error(`${schemaFile}: namespace is required`);

  const entities = [];
  const entityPattern = /\bentity\s+([A-Za-z_]\w*)(?:\s+extends\s+([A-Za-z_]\w*))?\s*\{([^}]*)\}/g;
  for (const match of clean.matchAll(entityPattern)) {
    const fields = [];
    const fieldPattern = /([A-Za-z_]\w*)\s*:\s*(u32|i32|i8|f32)\s*;/g;
    for (const field of match[3].matchAll(fieldPattern)) {
      fields.push({ name: field[1], type: field[2] });
    }
    entities.push({ name: match[1], parent: match[2], fields });
  }
  if (entities.length === 0) throw new Error(`${schemaFile}: no entity declarations`);
  return { namespace, entities };
}

function validateUnitSchema(schema) {
  const byName = new Map(schema.entities.map((entity) => [entity.name, entity]));
  const unit = byName.get("Unit");
  if (!unit || unit.parent !== "Entity") {
    throw new Error(`${schemaFile}: Unit must extend Entity`);
  }
  const fields = new Map([
    ...byName.get("Entity").fields,
    ...unit.fields,
  ].map((field) => [field.name, field.type]));
  const required = {
    id: "u32",
    instanceId: "u32",
    mapId: "u32",
    x: "f32",
    y: "f32",
    cellX: "i32",
    cellY: "i32",
    targetCellX: "i32",
    targetCellY: "i32",
    moveStartTick: "u32",
    moveEndTick: "u32",
    moving: "u32",
    speedCellsPerSecond: "f32",
    inputX: "i8",
    inputY: "i8",
    inputChanged: "u32",
    sequence: "u32",
  };
  for (const [name, type] of Object.entries(required)) {
    if (fields.get(name) !== type) {
      throw new Error(`${schemaFile}: ${name} must be ${type}`);
    }
  }
}

function renderRust(schema) {
  const rustType = { u32: "u32", i32: "i32", i8: "i8", f32: "f32" };
  const entities = schema.entities.map((entity) => {
    const fields = entity.fields
      .map((field) => `    pub ${toSnakeCase(field.name)}: ${rustType[field.type]},`)
      .join("\n");
    const parent = entity.parent
      ? `    pub ${toSnakeCase(entity.parent)}: ${entity.parent}Data,\n`
      : "";
    return `#[derive(Debug, Clone)]\npub struct ${entity.name}Data {\n${parent}${fields}\n}`;
  }).join("\n\n");
  return `// Generated by tools/codegen_native_data.mjs. Do not edit.\n#![allow(dead_code)]\n\n\
pub const NATIVE_DATA_NAMESPACE: &str = "${schema.namespace}";\n\n\
${entities}\n`;
}

function renderTypeScript() {
  return `// Generated by tools/codegen_native_data.mjs. Do not edit.\n\n\
import { Component } from "../../../core/runtime/entities";\n\
import { component } from "../../../core/runtime/metadata";\n\
import { NativeData } from "../../../demo/native/NativeData";\n\n\
export interface NativeUnitCreateArgs {\n\
  unitId: number;\n\
  instanceId: number;\n\
  mapId: number;\n\
  x: number;\n\
  y: number;\n\
}\n\n\
export interface NativeUnitSnapshot {\n\
  unitId: number;\n\
  x: number;\n\
  y: number;\n\
  acknowledgedSequence: number;\n\
  cellX: number;\n\
  cellY: number;\n\
  targetCellX: number;\n\
  targetCellY: number;\n\
  moveStartTick: number;\n\
  moveEndTick: number;\n\
  moving: boolean;\n\
}\n\n\
@component()\n\
export class NativeUnitRef extends Component<[args: NativeUnitCreateArgs]> {\n\
  private nativeHandle = 0;\n\n\
  get Handle(): number {\n\
    if (this.nativeHandle === 0) throw new Error("native Unit handle is not alive");\n\
    return this.nativeHandle;\n\
  }\n\n\
  protected override Awake(args: NativeUnitCreateArgs): void {\n\
    this.nativeHandle = NativeData.CreateUnit(args);\n\
  }\n\n\
  SetMovementInput(inputX: number, inputY: number, sequence: number): boolean {\n\
    return NativeData.SetMovementInput(this.Handle, inputX, inputY, sequence);\n\
  }\n\n\
  ResetMovement(): void {\n\
    NativeData.ResetMovement(this.Handle);\n\
  }\n\n\
  Snapshot(): NativeUnitSnapshot {\n\
    return NativeData.UnitSnapshot(this.Handle);\n\
  }\n\n\
  protected override OnDestroy(): void {\n\
    if (this.nativeHandle === 0) return;\n\
    NativeData.DestroyUnit(this.nativeHandle);\n\
    this.nativeHandle = 0;\n\
  }\n\
}\n`;
}

function toSnakeCase(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .toLowerCase();
}
