import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import process from "node:process";

import { loadGameModuleCatalog } from "./game_module_catalog.mjs";
import { publishModuleOutputs } from "./module_generated_outputs.mjs";

const root = path.resolve(import.meta.dirname, "..");
const moduleRoot = path.resolve(requiredArgument("--module-root"));
const checkOnly = process.argv.includes("--check");
const catalog = await loadGameModuleCatalog({
  projectRoot: root,
  modulesDirectory: path.dirname(moduleRoot),
});
const module = catalog.modules.find((candidate) => candidate.root === moduleRoot);
if (!module) throw new Error(`game module was not discovered: ${moduleRoot}`);
if (!module.gameConfig) {
  throw new Error(`game module ${module.id} does not declare gameConfig`);
}

const lubanDll = path.join(root, "tools", "third_party", "luban", "4.10.2", "Luban.dll");
const stagingRoot = await mkdtemp(path.join(os.tmpdir(), "tiangz-module-game-config-"));
try {
  const codeDirectory = path.join(stagingRoot, "code");
  const dataDirectory = path.join(stagingRoot, "data");
  await Promise.all([
    mkdir(codeDirectory, { recursive: true }),
    mkdir(dataDirectory, { recursive: true }),
  ]);
  run("dotnet", [
    lubanDll,
    "-t",
    module.gameConfig.target,
    "-c",
    "typescript-json",
    "-d",
    "json",
    "--validationFailAsError",
    "--conf",
    module.gameConfig.project,
    "-x",
    `outputCodeDir=${codeDirectory}`,
    "-x",
    `outputDataDir=${dataDirectory}`,
  ], module.root);

  const schema = normalizeText(await readFile(path.join(codeDirectory, "schema.ts"), "utf8"));
  const tableFiles = (await readdir(dataDirectory))
    .filter((name) => name.endsWith(".json"))
    .sort((left, right) => left.localeCompare(right, "en"));
  const tables = Object.fromEntries(await Promise.all(tableFiles.map(async (name) => [
    name.slice(0, -".json".length),
    JSON.parse(await readFile(path.join(dataDirectory, name), "utf8")),
  ])));
  const data = canonicalJson(tables);
  const schemaFingerprint = sha256(schema);
  const dataFingerprint = sha256(data);
  const sourceFingerprint = await fingerprintSources(
    path.dirname(module.gameConfig.project),
    [module.gameConfig.generatedCode, module.gameConfig.generatedData,
      ...(module.gameConfig.client ? [module.gameConfig.client.generatedCode, module.gameConfig.client.generatedData] : [])],
  );
  const manifest = canonicalJson({
    formatVersion: 1,
    moduleId: module.id,
    target: module.gameConfig.target,
    schemaFingerprint,
    dataFingerprint,
    sourceFingerprint,
    dataFile: "server.json",
    dataHash: dataFingerprint,
  });
  const fingerprintSource = `// Generated by tools/codegen_module_game_config.mjs. Do not edit.\n`
    + `export const ModuleGameConfigSchemaFingerprint = ${JSON.stringify(schemaFingerprint)};\n`;
  const expected = {
    code: new Map([
      ["schema.ts", schema],
      ["fingerprint.ts", fingerprintSource],
    ]),
    data: new Map([
      ["server.json", data],
      ["module-game-config.manifest.json", manifest],
    ]),
  };

  const outputGroups = [
    { directory: module.gameConfig.generatedCode, files: expected.code },
    { directory: module.gameConfig.generatedData, files: expected.data },
  ];
  if (module.gameConfig.client) {
    const client = module.gameConfig.client;
    const code = path.join(stagingRoot, "client-code");
    const dataDir = path.join(stagingRoot, "client-data");
    run("dotnet", [lubanDll, "-t", client.target, "-c", "typescript-json", "-d", "json",
      "--validationFailAsError", "--conf", module.gameConfig.project,
      "-x", `outputCodeDir=${code}`, "-x", `outputDataDir=${dataDir}`], module.root);
    const clientSchema = normalizeText(await readFile(path.join(code, "schema.ts"), "utf8"));
    const names = (await readdir(dataDir)).filter((name) => name.endsWith(".json")).sort();
    const clientTables = Object.fromEntries(await Promise.all(names.map(async (name) => [
      name.slice(0, -5), JSON.parse(await readFile(path.join(dataDir, name), "utf8")),
    ])));
    const clientData = canonicalJson(clientTables);
    const clientCodeFiles = new Map([["schema.ts", clientSchema]]);
    const clientDataFiles = new Map([
      ["client.json", clientData],
      ["module-game-config.manifest.json", canonicalJson({
        formatVersion: 1, moduleId: module.id, target: client.target,
        schemaFingerprint: sha256(clientSchema), dataFingerprint: sha256(clientData),
        dataFile: "client.json", dataHash: sha256(clientData),
      })],
    ]);
    outputGroups.push({ directory: client.generatedCode, files: clientCodeFiles }, { directory: client.generatedData, files: clientDataFiles });
  }
  await publishModuleOutputs(module.root, outputGroups, checkOnly);
  process.stdout.write(`[codegen:module-game-config] ${checkOnly ? "checked" : "generated"} module=${module.id} schema=${schemaFingerprint.slice(0, 12)} data=${dataFingerprint.slice(0, 12)}\n`);
} finally {
  await rm(stagingRoot, { recursive: true, force: true });
}

async function fingerprintSources(directory, excludedDirectories) {
  const hashes = [];
  await visit(directory);
  return sha256(hashes.join("\0"));

  async function visit(parent) {
    const entries = await readdir(parent, { withFileTypes: true });
    for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name, "en"))) {
      const file = path.join(parent, entry.name);
      if (excludedDirectories.some((excluded) => isWithin(excluded, file))) continue;
      if (entry.isDirectory()) {
        await visit(file);
        continue;
      }
      if (!entry.isFile()) continue;
      const relative = path.relative(directory, file).replaceAll(path.sep, "/");
      hashes.push(`${relative}:${sha256(await readFile(file))}`);
    }
  }
}

function run(command, argumentsList, cwd) {
  const result = spawnSync(command, argumentsList, {
    cwd,
    env: process.env,
    stdio: "inherit",
    shell: false,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} failed with code=${result.status} signal=${result.signal ?? "none"}`);
  }
}

function requiredArgument(name) {
  const prefix = `${name}=`;
  const inline = process.argv.find((value) => value.startsWith(prefix));
  if (inline) return inline.slice(prefix.length);
  const index = process.argv.indexOf(name);
  const value = index >= 0 ? process.argv[index + 1] : undefined;
  if (!value || value.startsWith("--")) throw new Error(`${name} is required`);
  return value;
}

function isWithin(directory, candidate) {
  const relative = path.relative(path.resolve(directory), path.resolve(candidate));
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function canonicalJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function normalizeText(value) {
  return value.replaceAll("\r\n", "\n").replace(/[ \t]+$/gm, "");
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}
