import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import process from "node:process";

import { loadGameModuleCatalog } from "./game_module_catalog.mjs";

const root = path.resolve(import.meta.dirname, "..");
const moduleRoot = path.resolve(requiredArgument("--module-root"));
const checkOnly = process.argv.includes("--check");
const catalog = await loadGameModuleCatalog({
  projectRoot: root,
  modulesDirectory: path.dirname(moduleRoot),
});
const module = catalog.modules.find((candidate) => candidate.root === moduleRoot);
if (!module) throw new Error(`game module was not discovered: ${moduleRoot}`);
if (!module.gameConfig) {
  throw new Error(`game module ${module.id} does not declare gameConfig`);
}

const lubanDll = path.join(root, "tools", "third_party", "luban", "4.10.2", "Luban.dll");
const stagingRoot = await mkdtemp(path.join(os.tmpdir(), "tiangz-module-game-config-"));
try {
  const codeDirectory = path.join(stagingRoot, "code");
  const dataDirectory = path.join(stagingRoot, "data");
  await Promise.all([
    mkdir(codeDirectory, { recursive: true }),
    mkdir(dataDirectory, { recursive: true }),
  ]);
  run("dotnet", [
    lubanDll,
    "-t",
    module.gameConfig.target,
    "-c",
    "typescript-json",
    "-d",
    "json",
    "--validationFailAsError",
    "--conf",
    module.gameConfig.project,
    "-x",
    `outputCodeDir=${codeDirectory}`,
    "-x",
    `outputDataDir=${dataDirectory}`,
  ], module.root);

  const schema = normalizeText(await readFile(path.join(codeDirectory, "schema.ts"), "utf8"));
  const tableFiles = (await readdir(dataDirectory))
    .filter((name) => name.endsWith(".json"))
    .sort((left, right) => left.localeCompare(right, "en"));
  const tables = Object.fromEntries(await Promise.all(tableFiles.map(async (name) => [
    name.slice(0, -".json".length),
    JSON.parse(await readFile(path.join(dataDirectory, name), "utf8")),
  ])));
  const data = canonicalJson(tables);
  const schemaFingerprint = sha256(schema);
  const dataFingerprint = sha256(data);
  const sourceFingerprint = await fingerprintSources(
    path.dirname(module.gameConfig.project),
    [module.gameConfig.generatedCode, module.gameConfig.generatedData],
  );
  const manifest = canonicalJson({
    formatVersion: 1,
    moduleId: module.id,
    target: module.gameConfig.target,
    schemaFingerprint,
    dataFingerprint,
    sourceFingerprint,
    dataFile: "server.json",
    dataHash: dataFingerprint,
  });
  const fingerprintSource = `// Generated by tools/codegen_module_game_config.mjs. Do not edit.\n`
    + `export const ModuleGameConfigSchemaFingerprint = ${JSON.stringify(schemaFingerprint)};\n`;
  const expected = {
    code: new Map([
      ["schema.ts", schema],
      ["fingerprint.ts", fingerprintSource],
    ]),
    data: new Map([
      ["server.json", data],
      ["module-game-config.manifest.json", manifest],
    ]),
  };

  if (checkOnly) {
    await verifyOutput(module.gameConfig.generatedCode, expected.code);
    await verifyOutput(module.gameConfig.generatedData, expected.data);
    process.stdout.write(
      `[codegen:module-game-config] checked module=${module.id} schema=${schemaFingerprint.slice(0, 12)} data=${dataFingerprint.slice(0, 12)}\n`,
    );
  } else {
    await publishDirectory(module.gameConfig.generatedCode, expected.code);
    await publishDirectory(module.gameConfig.generatedData, expected.data);
    process.stdout.write(
      `[codegen:module-game-config] generated module=${module.id} schema=${schemaFingerprint.slice(0, 12)} data=${dataFingerprint.slice(0, 12)}\n`,
    );
  }
} finally {
  await rm(stagingRoot, { recursive: true, force: true });
}

/** 原子替换声明的生成目录，避免混入旧Schema文件。 / Atomically replaces the declared generated directory so stale schema files cannot survive. */
async function publishDirectory(directory, files) {
  const building = `${directory}.building-${process.pid}`;
  await rm(building, { recursive: true, force: true });
  await mkdir(building, { recursive: true });
  for (const [name, contents] of files) {
    await writeFile(path.join(building, name), contents, "utf8");
  }
  await rm(directory, { recursive: true, force: true });
  await mkdir(path.dirname(directory), { recursive: true });
  await rename(building, directory);
}

async function verifyOutput(directory, expected) {
  const actualNames = (await readdir(directory)).sort((left, right) => left.localeCompare(right, "en"));
  const expectedNames = [...expected.keys()].sort((left, right) => left.localeCompare(right, "en"));
  if (JSON.stringify(actualNames) !== JSON.stringify(expectedNames)) {
    throw new Error(`generated module game config files are stale: ${directory}`);
  }
  for (const [name, contents] of expected) {
    const actual = await readFile(path.join(directory, name), "utf8");
    if (actual !== contents) throw new Error(`generated module game config is stale: ${path.join(directory, name)}`);
  }
}

async function fingerprintSources(directory, excludedDirectories) {
  const hashes = [];
  await visit(directory);
  return sha256(hashes.join("\0"));

  async function visit(parent) {
    const entries = await readdir(parent, { withFileTypes: true });
    for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name, "en"))) {
      const file = path.join(parent, entry.name);
      if (excludedDirectories.some((excluded) => isWithin(excluded, file))) continue;
      if (entry.isDirectory()) {
        await visit(file);
        continue;
      }
      if (!entry.isFile()) continue;
      const relative = path.relative(directory, file).replaceAll(path.sep, "/");
      hashes.push(`${relative}:${sha256(await readFile(file))}`);
    }
  }
}

function run(command, argumentsList, cwd) {
  const result = spawnSync(command, argumentsList, {
    cwd,
    env: process.env,
    stdio: "inherit",
    shell: false,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} failed with code=${result.status} signal=${result.signal ?? "none"}`);
  }
}

function requiredArgument(name) {
  const prefix = `${name}=`;
  const inline = process.argv.find((value) => value.startsWith(prefix));
  if (inline) return inline.slice(prefix.length);
  const index = process.argv.indexOf(name);
  const value = index >= 0 ? process.argv[index + 1] : undefined;
  if (!value || value.startsWith("--")) throw new Error(`${name} is required`);
  return value;
}

function isWithin(directory, candidate) {
  const relative = path.relative(path.resolve(directory), path.resolve(candidate));
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function canonicalJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function normalizeText(value) {
  return value.replaceAll("\r\n", "\n").replace(/[ \t]+$/gm, "");
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}
