import { readFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import path from "node:path";
import { assertValidNativeWorkspace, nativeRustOperationName } from "@tiangz/native-language-core";
import { generateNativeFiles } from "@tiangz/native-language-core/codegen";
import { loadGameModuleCatalog } from "./game_module_catalog.mjs";
import { collectNativeFiles } from "./module_native.mjs";
import { publishModuleOutputs } from "./module_generated_outputs.mjs";

const root = path.resolve(import.meta.dirname, "..");
const index = process.argv.indexOf("--modules-dir");
const check = process.argv.includes("--check");
const catalog = await loadGameModuleCatalog({ projectRoot: root,
  modulesDirectory: path.resolve(root, index >= 0 ? process.argv[index + 1] : process.env.TIANGZ_MODULES_DIR ?? "modules") });
for (const module of catalog.modules.filter((item) => item.native)) {
  const config = module.native;
  const sources = await Promise.all((await collectNativeFiles(config.source)).filter((file) => file.endsWith(".native"))
    .map(async (uri) => ({ uri, text: await readFile(uri, "utf8") })));
  const schema = assertValidNativeWorkspace(sources);
  // 纯 op 模块不需要实体 Store；避免生成空枚举的数据访问器。 / Op-only modules need no entity Store or empty-enum accessors.
  const hasEntityData = schema.entities.some(entity => !entity.abstract);
  const rustRoot = config.relative.generatedRust;
  const workers = config.relative.workers ?? [];
  const workerOnly = schema.operations.length === 0 && workers.length > 0 && !hasEntityData;
  const globalName = `__etsModuleNative_${createHash("sha256").update(module.id).digest("hex")}`;
  const files = (workerOnly ? [
    { relativePath: `${rustRoot}/native_ops.rs`, format: "rust", content: '// Generated by tools/codegen_module_native.mjs. Do not edit.\ndeno_core::extension!(native_data_host);\npub(crate) fn init() -> deno_core::Extension { native_data_host::init() }\npub(crate) const BOOTSTRAP_SOURCE: &str = include_str!("native_ops_bootstrap.js");\n' },
    { relativePath: `${rustRoot}/native_ops_bootstrap.js`, format: "javascript", content: '// Generated by tools/codegen_module_native.mjs. Do not edit.\n' },
  ] : generateNativeFiles(schema, {
    generatedBy: "tools/codegen_module_native.mjs", rustDataPath: `${rustRoot}/native_data.rs`,
    rustOpsPath: `${rustRoot}/native_ops.rs`, bootstrapPath: `${rustRoot}/native_ops_bootstrap.js`,
    typeScriptRoot: config.relative.generatedTypeScript,
    componentBaseImport: "#tiangz/core", componentDecoratorImport: "#tiangz/core", persistenceRuntimeImport: "#tiangz/core",
  })).filter(file => hasEntityData || file.relativePath !== `${rustRoot}/native_data.rs`).map((file) => {
    // 固定版本后端的宿主绑定投影；实体布局和Codec保持原生成器输出。
    // Project fixed-version backend host bindings; entity layouts and codecs retain generator output.
    let content = file.content.replaceAll("__etsNativeOps", globalName);
    if (file.relativePath.endsWith("native_ops_bootstrap.js")) {
      for (const op of schema.operations) {
        const name = nativeRustOperationName(op.name);
        content = content.replaceAll(`core.ops.${name}(`, `core.ops[${JSON.stringify(`${module.id}::${name}`)}](`);
      }
    }
    return { ...file, content };
  });
  const names = schema.operations.map((op) => nativeRustOperationName(op.name));
  if (workers.length) {
    const workerGlobal = `${globalName}_workers`;
    const bootstrap = files.find(file => file.relativePath.endsWith("native_ops_bootstrap.js"));
    bootstrap.content += `\nObject.defineProperty(globalThis, ${JSON.stringify(workerGlobal)}, { value: Object.freeze({\n${workers.map(worker => {
      const name = JSON.stringify(`${module.id}::${worker.name}`);
      return `${worker.name}: Object.freeze({ call: input => Deno.core.ops.op_native_worker_call(${name}, input), drain: () => Deno.core.ops.op_native_worker_drain(${name}), stats: () => Deno.core.ops.op_native_worker_stats(${name}) })`;
    }).join(",\n")}\n}) });\n`;
    files.push({ relativePath: `${config.relative.generatedTypeScript}/NativeWorkers.ts`, format: "typescript", content:
      `// Generated by tools/codegen_module_native.mjs. Do not edit.\n` +
      `export interface NativeWorkerStats { readonly accepting: boolean; readonly pending: number; readonly running: boolean; readonly completed: number; readonly rejected: number; readonly failed: number; readonly waitMicros: number; readonly computeMicros: number; }\n` +
      `export interface NativeWorker { call(input: string): Promise<string>; drain(): Promise<void>; stats(): NativeWorkerStats; }\n` +
      `declare global { var ${workerGlobal}: { ${workers.map(worker => `readonly ${worker.name}: NativeWorker;`).join(" ")} }; }\n` +
      `declare global { var __tiangzModuleNativeFingerprint: string; }\nexport const NativeWorkerBuildFingerprint = globalThis.__tiangzModuleNativeFingerprint;\n` +
      `export const NativeWorkers = globalThis.${workerGlobal};\n` });
  }
  files.push({ relativePath: `${rustRoot}/mod.rs`, format: "rust", content:
    `// Generated by tools/codegen_module_native.mjs. Do not edit.\n${hasEntityData ? "pub mod native_data;\n" : ""}mod native_ops;\n` +
    `pub const BOOTSTRAP: &str = native_ops::BOOTSTRAP_SOURCE;\npub fn extension() -> deno_core::Extension {\n` +
    `let mut extension = native_ops::init();\nextension.name = ${JSON.stringify(module.id)};\n` +
    (names.length ? `for op in extension.ops.to_mut() { (op.name, op.name_fast) = match op.name {\n` +
    names.map((name) => `${JSON.stringify(name)} => (${JSON.stringify(`${module.id}::${name}`)}, deno_core::ascii_str!(${JSON.stringify(`${module.id}::${name}`)})),`).join("\n") +
    `\n_ => panic!("undeclared module native op"),\n}; }\n` : '') + `extension\n}\n` });
  const outputGroups = [config.generatedRust, config.generatedTypeScript].map((directory) => ({ directory, files: new Map() }));
  for (const file of files) {
    const destination = path.resolve(module.root, file.relativePath);
    const relative = path.relative(module.root, destination);
    if (relative.startsWith("..") || path.isAbsolute(relative)) throw new Error("native output escapes module");
    let content = file.content;
    if (file.format === "rust") {
      const result = spawnSync("rustfmt", ["--edition", "2024", "--emit", "stdout"], { cwd: root, input: content, encoding: "utf8", windowsHide: true });
      if (result.error) throw result.error;
      if (result.status !== 0) throw new Error(result.stderr);
      content = result.stdout;
    }
    const group = outputGroups.find((group) => group.directory === path.dirname(destination));
    if (!group) throw new Error("Native generator returned an undeclared output");
    group.files.set(path.basename(destination), content);
  }
  await publishModuleOutputs(module.root, outputGroups, check);
  process.stdout.write(`[module-native] ${check ? "checked" : "generated"} ${module.id}\n`);
}
