import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadGameModuleCatalog } from "./game_module_catalog.mjs";
import { collectFiles, generateSystemDeclarations } from "./system_declarations.mjs";

const root = path.resolve(import.meta.dirname, "..");
const args = process.argv.slice(2);
const check = args.includes("--check");
const index = args.indexOf("--modules-dir");
const catalog = await loadGameModuleCatalog({ projectRoot: root,
  modulesDirectory: path.resolve(root, index < 0 ? process.env.TIANGZ_MODULES_DIR ?? "modules" : args[index + 1]) });
const selected = args.indexOf("--module");
const header = "// Generated by tools/codegen_module_systems.mjs. Do not edit.\n";
for (const module of catalog.modules) {
  if (selected >= 0 && module.id !== args[selected + 1]) continue;
  const modelRoot = module.entries.modelRoots[0];
  const hotfixRoot = module.entries.hotfixRoots[0];
  const bootstrap = path.join(modelRoot, "generated/bootstrap");
  const hotfixOutput = path.join(hotfixRoot, "generated/bootstrap/index.ts");
  const files = await collectFiles(module.entries.hotfixRoots);
  const generated = await generateSystemDeclarations({ root: module.root,
    check,
    files: files.filter(file => file.endsWith("System.ts")), modelRoots: module.entries.modelRoots,
    sharedModelRoots: [path.join(root, "app/model/domains")],
    outputRoot: path.join(bootstrap, "systems"), publicFile: module.publicApi?.file ?? module.entries.model });
  const imports = generated.targets.map((target, i) => `import { ${target.name} as Target${i} } from ${JSON.stringify(target.file.startsWith(path.join(root, "app/model/domains")) ? "#tiangz/domains" : specifier(target.file, bootstrap))};`);
  const scenes = (await collectFiles(module.entries.modelRoots)).filter(file => path.basename(path.dirname(file)) === "scenes");
  const output = `${header}${scenes.map(file => `import ${JSON.stringify(specifier(file, bootstrap))};`).join("\n")}\n${imports.join("\n")}\n` +
    `export const modelTypes = { ${generated.targets.map((target, i) => `${target.name}: Target${i}`).join(", ")} };\n` +
    `export const requiredSystems = [${generated.targets.map((_, i) => `Target${i}`).join(", ")}];\n`;
  await publish(path.join(bootstrap, "index.ts"), output);
  await publish(hotfixOutput, header + files.filter(file => file !== module.entries.hotfix)
    .map(file => `import ${JSON.stringify(specifier(file, path.dirname(hotfixOutput)))};`).join("\n") + "\n");
  await publish(path.join(path.dirname(hotfixOutput), "handlers.ts"), header + files.filter(file => file.split(path.sep).includes("handlers"))
    .map(file => `import ${JSON.stringify(specifier(file, path.dirname(hotfixOutput)))};`).join("\n") + "\n");
  console.log(`[module-systems] ${module.id} systems=${generated.targets.length}`);
}

function specifier(file, directory) {
  const relative = path.relative(directory, file).replaceAll(path.sep, "/").replace(/\.ts$/, "");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

async function publish(file, content) {
  try {
    const previous = await readFile(file, "utf8");
    if (!previous.startsWith("// Generated by tools/codegen_")) throw new Error(`refusing to overwrite handwritten module entry: ${file}`);
    if (check && previous !== content) throw new Error(`stale module bootstrap: ${file}`);
  } catch (error) { if (error.code !== "ENOENT" || check) throw error; }
  if (check) return;
  await mkdir(path.dirname(file), { recursive: true });
  await writeFile(file, content);
}
