import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  mkdir,
  readFile,
  readdir,
  rm,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { collectGeneratedFiles, recordGenerator } from "./codegen_manifest.mjs";

const scriptFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptFile), "..");
const configRoot = path.join(root, "game_config");
const lubanDll = path.join(root, "tools", "third_party", "luban", "4.10.2", "Luban.dll");
const stagingRoot = path.join(root, "temp", "game-config-codegen");
const serverOutput = path.join(root, "app", "generated", "model", "config");
const clientOutput = path.join(root, "client_sdk", "typescript", "Generated", "Config");
const dataOutput = path.join(configRoot, "generated");
const sources = await collectSources(configRoot);

await rm(stagingRoot, { recursive: true, force: true });
await mkdir(stagingRoot, { recursive: true });

let dataFingerprint;
try {
  const generated = {
    server: await generateTarget("server"),
    client: await generateTarget("client"),
  };
  const serverSchemaFingerprint = sha256(generated.server.schema);
  const clientSchemaFingerprint = sha256(generated.client.schema);
  const serverData = canonicalJson(generated.server.data);
  const clientData = canonicalJson(generated.client.data);
  dataFingerprint = sha256(`${serverData}\0${clientData}`);
  const manifest = {
    formatVersion: 1,
    schemaFingerprint: serverSchemaFingerprint,
    clientSchemaFingerprint,
    dataFingerprint,
    serverFile: "server.json",
    serverHash: sha256(serverData),
    clientFile: "client.json",
    clientHash: sha256(clientData),
  };
  await writeDataPackage(manifest, serverData, clientData);
  await writeTarget("server", serverOutput, generated.server, {
    schemaFingerprint: serverSchemaFingerprint,
  });
  await writeTarget("client", clientOutput, generated.client, {
    dataFingerprint,
  });
} finally {
  await rm(stagingRoot, { recursive: true, force: true });
}

const outputRoots = [
  ...[serverOutput, clientOutput].map((outputPath) => ({
    path: outputPath,
    extensions: [".ts"],
  })),
  { path: dataOutput, extensions: [".json"] },
];
await recordGenerator(root, {
  id: "game-config",
  command: "npm run codegen:game-config",
  contentInputs: [scriptFile, lubanDll, ...sources],
  outputs: await collectGeneratedFiles(outputRoots),
  outputRoots,
});

console.log(`[codegen:game-config] generated schema and data package fingerprint=${dataFingerprint.slice(0, 12)}`);

async function generateTarget(target) {
  const codeDirectory = path.join(stagingRoot, target, "code");
  const dataDirectory = path.join(stagingRoot, target, "data");
  await mkdir(codeDirectory, { recursive: true });
  await mkdir(dataDirectory, { recursive: true });

  run("dotnet", [
    lubanDll,
    "-t",
    target,
    "-c",
    "typescript-json",
    "-d",
    "json",
    "--conf",
    path.join(configRoot, "luban.conf"),
    "-x",
    `outputCodeDir=${codeDirectory}`,
    "-x",
    `outputDataDir=${dataDirectory}`,
  ]);

  const schema = normalizeText(await readFile(path.join(codeDirectory, "schema.ts"), "utf8"));
  const dataFiles = (await readdir(dataDirectory))
    .filter((name) => name.endsWith(".json"))
    .sort((left, right) => left.localeCompare(right, "en"));
  const data = Object.fromEntries(await Promise.all(dataFiles.map(async (name) => [
    name.slice(0, -".json".length),
    JSON.parse(await readFile(path.join(dataDirectory, name), "utf8")),
  ])));

  return { schema, data };
}

async function writeDataPackage(manifest, serverData, clientData) {
  await rm(dataOutput, { recursive: true, force: true });
  await mkdir(dataOutput, { recursive: true });
  await writeFile(path.join(dataOutput, "server.json"), serverData, "utf8");
  await writeFile(path.join(dataOutput, "client.json"), clientData, "utf8");
  await writeFile(
    path.join(dataOutput, "game-config.manifest.json"),
    canonicalJson(manifest),
    "utf8",
  );
}

async function writeTarget(target, outputRoot, generated, fingerprints) {
  await rm(outputRoot, { recursive: true, force: true });
  await mkdir(outputRoot, { recursive: true });
  await writeFile(path.join(outputRoot, "schema.ts"), generated.schema, "utf8");
  await writeFile(
    path.join(outputRoot, "GameConfigs.ts"),
    target === "server"
      ? createServerFacade(fingerprints.schemaFingerprint)
      : createClientFacade(generated.data, fingerprints.dataFingerprint),
    "utf8",
  );
  await writeFile(
    path.join(outputRoot, "index.ts"),
    `// Generated by tools/codegen_game_config.mjs. Do not edit.\nexport * from "./GameConfigs";\nexport { SpatialMode, game } from "./schema";\n`,
    "utf8",
  );
}

function createServerFacade(schemaFingerprint) {
  return `// Generated by tools/codegen_game_config.mjs for server. Do not edit.
import { SpatialMode, Tables, type game } from "./schema";

export interface GameConfigManifest {
  readonly formatVersion: number;
  readonly schemaFingerprint: string;
  readonly dataFingerprint: string;
}

export interface GameConfigInstallResult {
  readonly previousFingerprint?: string;
  readonly dataFingerprint: string;
}

class ConfigTable<T extends { readonly id: number }> {
  private readonly byId: ReadonlyMap<number, T>;
  private readonly values: readonly T[];

  constructor(values: readonly T[]) {
    const copy = values.map((value) => Object.freeze(value));
    this.values = Object.freeze(copy);
    this.byId = new Map(copy.map((value) => [value.id, value]));
  }

  Get(id: number): T {
    const value = this.byId.get(id);
    if (!value) throw new Error(\`game config not found: id=\${id}\`);
    return value;
  }

  TryGet(id: number): T | undefined {
    return this.byId.get(id);
  }

  GetAll(): readonly T[] {
    return this.values;
  }
}

export type ItemConfig = game.ItemConfig;
export type MapConfig = game.MapConfig;
export type PlayerConfig = game.PlayerConfig;

interface GameConfigSnapshot {
  readonly dataFingerprint: string;
  readonly ItemConfig: ConfigTable<game.ItemConfig>;
  readonly MapConfig: ConfigTable<game.MapConfig>;
  readonly PlayerConfig: ConfigTable<game.PlayerConfig>;
}

export const GameConfigSchemaFingerprint = "${schemaFingerprint}";

export class GameConfigRegistry {
  private static current: GameConfigSnapshot | undefined;

  static get CurrentFingerprint(): string | undefined {
    return this.current?.dataFingerprint;
  }

  static Install(manifestJson: string, dataJson: string): GameConfigInstallResult {
    const manifest = JSON.parse(manifestJson) as GameConfigManifest;
    if (manifest.formatVersion !== 1) {
      throw new Error(\`unsupported game config manifest format: \${manifest.formatVersion}\`);
    }
    if (manifest.schemaFingerprint !== GameConfigSchemaFingerprint) {
      throw new Error(
        \`game config schema mismatch: model=\${GameConfigSchemaFingerprint}, candidate=\${manifest.schemaFingerprint}\`,
      );
    }
    if (!/^[0-9a-f]{64}$/.test(manifest.dataFingerprint)) {
      throw new Error("game config data fingerprint must be lowercase sha256");
    }

    const rawData = JSON.parse(dataJson) as Record<string, unknown>;
    const tables = new Tables((file) => {
      const value = rawData[file];
      if (value === undefined) throw new Error(\`game config data not found: \${file}\`);
      return value;
    });
    const candidate: GameConfigSnapshot = Object.freeze({
      dataFingerprint: manifest.dataFingerprint,
      ItemConfig: new ConfigTable<game.ItemConfig>(tables.TbItemConfig.getDataList()),
      MapConfig: new ConfigTable<game.MapConfig>(tables.TbMapConfig.getDataList()),
      PlayerConfig: new ConfigTable<game.PlayerConfig>(tables.TbPlayerConfig.getDataList()),
    });
    validateSnapshot(candidate);

    const previousFingerprint = this.current?.dataFingerprint;
    this.current = candidate;
    return {
      ...(previousFingerprint ? { previousFingerprint } : {}),
      dataFingerprint: candidate.dataFingerprint,
    };
  }

  static RequireCurrent(): GameConfigSnapshot {
    if (!this.current) throw new Error("game config data is not installed");
    return this.current;
  }
}

export const GameConfigs = Object.freeze({
  get ItemConfig() { return GameConfigRegistry.RequireCurrent().ItemConfig; },
  get MapConfig() { return GameConfigRegistry.RequireCurrent().MapConfig; },
  get PlayerConfig() { return GameConfigRegistry.RequireCurrent().PlayerConfig; },
});

function validateSnapshot(snapshot: GameConfigSnapshot): void {
  for (const map of snapshot.MapConfig.GetAll()) {
    if (![map.spawnX, map.spawnY, map.spawnZ, map.spawnYaw, map.aoiCellSizeMeters].every(Number.isFinite)) {
      throw new Error(\`map config \${map.id} contains a non-finite spatial value\`);
    }
    if (map.aoiCellSizeMeters <= 0) {
      throw new Error(\`map config \${map.id} must use a positive AOI cell size\`);
    }
    if (map.spatialMode === SpatialMode.Grid2D) {
      if (map.widthCells < 3 || map.depthCells < 3 || map.gridCellSizeMeters <= 0) {
        throw new Error(\`Grid2D map config \${map.id} has invalid dimensions or cell size\`);
      }
    } else if (map.spatialMode === SpatialMode.NavMesh3D) {
      if (!map.navigationAsset || !map.navigationVersion || !/^[0-9a-f]{64}$/.test(map.navigationHash)) {
        throw new Error(\`NavMesh3D map config \${map.id} needs an asset, version, and lowercase SHA-256\`);
      }
    } else {
      throw new Error(\`map config \${map.id} has unsupported spatial mode \${map.spatialMode}\`);
    }
  }
  for (const player of snapshot.PlayerConfig.GetAll()) {
    if (!player.initialMapId_ref || !player.initialItemConfigId_ref) {
      throw new Error(\`player config \${player.id} contains a missing reference\`);
    }
    if (player.initialHp < 0 || player.maxHp <= 0 || player.initialHp > player.maxHp) {
      throw new Error(\`player config \${player.id} has invalid hp values\`);
    }
    if (player.moveSpeed <= 0 || player.initialItemCount < 0) {
      throw new Error(\`player config \${player.id} has invalid movement or item values\`);
    }
  }
}
`;
}

function createClientFacade(data, dataFingerprint) {
  return `// Generated by tools/codegen_game_config.mjs for client. Do not edit.
import { Tables, type game } from "./schema";

const RAW_DATA: Record<string, unknown> = ${JSON.stringify(data, null, 2)};

class ConfigTable<T extends { readonly id: number }> {
  private readonly byId: ReadonlyMap<number, T>;
  private readonly values: readonly T[];

  constructor(values: readonly T[]) {
    const copy = values.map((value) => Object.freeze(value));
    this.values = Object.freeze(copy);
    this.byId = new Map(copy.map((value) => [value.id, value]));
  }

  Get(id: number): T {
    const value = this.byId.get(id);
    if (!value) throw new Error(\`game config not found: id=\${id}\`);
    return value;
  }

  TryGet(id: number): T | undefined {
    return this.byId.get(id);
  }

  GetAll(): readonly T[] {
    return this.values;
  }
}

const tables = new Tables((file) => {
  const value = RAW_DATA[file];
  if (value === undefined) throw new Error(\`game config data not found: \${file}\`);
  return value;
});

export type ItemConfig = game.ItemConfig;
export type MapConfig = game.MapConfig;
export type PlayerConfig = game.PlayerConfig;

export const GameConfigFingerprint = "${dataFingerprint}";
export const GameConfigs = Object.freeze({
  ItemConfig: new ConfigTable<game.ItemConfig>(tables.TbItemConfig.getDataList()),
  MapConfig: new ConfigTable<game.MapConfig>(tables.TbMapConfig.getDataList()),
  PlayerConfig: new ConfigTable<game.PlayerConfig>(tables.TbPlayerConfig.getDataList()),
});
`;
}

function run(command, args) {
  const result = spawnSync(command, args, {
    cwd: root,
    env: process.env,
    stdio: "inherit",
    shell: false,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    throw new Error(`${command} failed with code=${result.status} signal=${result.signal ?? "none"}`);
  }
}

async function collectSources(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await collectSources(fullPath));
    else if (entry.isFile() && isGeneratorInput(fullPath)) files.push(fullPath);
  }
  return files.sort((left, right) => left.localeCompare(right, "en"));
}

function isGeneratorInput(file) {
  return [".conf", ".xml", ".xlsx"].includes(path.extname(file).toLowerCase());
}

function canonicalJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function normalizeText(value) {
  return value.replaceAll("\r\n", "\n");
}
