import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { recordGenerator } from "./codegen_manifest.mjs";

const scriptFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptFile), "..");
const outputFile = path.join(root, "app", "generated", "hotfix", "scenes.ts");
const handlerOutputFile = path.join(root, "app", "generated", "hotfix", "handlers.ts");
const configFile = path.join(root, "codegen.config.json");

const config = await readCodegenConfig();
const sceneSearchRoots = resolveSearchRoots(
  config.hotfix?.sceneSearchRoots ?? ["app"],
);
const handlerSearchRoots = resolveSearchRoots(
  config.hotfix?.handlerSearchRoots ?? config.hotfix?.sceneSearchRoots ?? ["app"],
);
const serverProtocolSearchRoots = resolveSearchRoots(
  config.hotfix?.serverProtocolSearchRoots ?? ["app/generated/model/server"],
);

function toImportPath(file, generatedFile = outputFile) {
  const fromOutputDir = path.relative(path.dirname(generatedFile), file);
  const withoutExt = fromOutputDir.replace(/\.ts$/, "");
  return withoutExt.startsWith(".")
    ? withoutExt.replaceAll(path.sep, "/")
    : `./${withoutExt.replaceAll(path.sep, "/")}`;
}

async function readCodegenConfig() {
  try {
    const text = await readFile(configFile, "utf8");
    return JSON.parse(text);
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return {};
    }
    throw error;
  }
}

function resolveSearchRoots(items) {
  return items.map((item) => path.resolve(root, item));
}

async function collectFiles(searchRoots, predicate) {
  const files = [];

  for (const dir of searchRoots) {
    await collectFilesInDir(dir, predicate, files);
  }

  return files.sort((a, b) => a.localeCompare(b));
}

async function collectFilesInDir(dir, predicate, files) {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (error) {
    if (error && typeof error === "object" && "code" in error && error.code === "ENOENT") {
      return;
    }
    throw error;
  }

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (shouldSkipDir(entry.name)) continue;
      await collectFilesInDir(fullPath, predicate, files);
      continue;
    }
    if (entry.isFile() && predicate(fullPath)) {
      files.push(fullPath);
    }
  }
}

function shouldSkipDir(name) {
  return name === "generated" || name === "dist" || name === "node_modules";
}

function isSceneFile(file) {
  return (
    path.basename(file) !== "index.ts" &&
    file.endsWith(".ts") &&
    path.basename(path.dirname(file)) === "scenes"
  );
}

function isHandlerFile(file) {
  return (
    path.basename(file) !== "index.ts" &&
    file.endsWith(".ts") &&
    path.normalize(file).split(path.sep).includes("handlers")
  );
}

function isServerProtocolRpcsFile(file) {
  return (
    path.basename(file) === "rpcs.ts" &&
    path.basename(path.dirname(file)) === "protocol"
  );
}

function isServerProtocolMessagesFile(file) {
  return (
    path.basename(file) === "messageDescriptors.ts" &&
    path.basename(path.dirname(file)) === "protocol"
  );
}

const sceneFiles = await collectFiles(sceneSearchRoots, isSceneFile);
const handlerFiles = await collectFiles(handlerSearchRoots, isHandlerFile);
const protocolFiles = await collectFiles(
  serverProtocolSearchRoots,
  isServerProtocolRpcsFile,
);
const messageProtocolFiles = await collectFiles(
  serverProtocolSearchRoots,
  isServerProtocolMessagesFile,
);

const protocolImports = protocolFiles
  .map(
    (file, index) =>
      `import { AllRpcDescriptors as RpcDescriptors${index} } from "${toImportPath(file)}";`,
  )
  .join("\n");
const sceneImports = sceneFiles
  .map((file) => `import "${toImportPath(file)}";`)
  .join("\n");
const messageProtocolImports = messageProtocolFiles
  .map(
    (file, index) =>
      `import { AllMessageDescriptors as MessageDescriptors${index} } from "${toImportPath(file)}";`,
  )
  .join("\n");
const registerCalls = protocolFiles
  .map((_, index) => `registerKnownRpcs(RpcDescriptors${index});`)
  .join("\n");
const registerMessageCalls = messageProtocolFiles
  .map((_, index) => `registerKnownMessages(MessageDescriptors${index});`)
  .join("\n");
const content = `// Generated by tools/codegen_scenes.mjs. Do not edit by hand.
import { registerKnownRpcs } from "../../core/protocol/rpc";
import { registerKnownMessages } from "../../core/protocol/message";
${protocolImports}
${messageProtocolImports}
${sceneImports}

${registerCalls}
${registerMessageCalls}
`;
const handlerContent = `// Generated by tools/codegen_scenes.mjs. Do not edit by hand.
${handlerFiles
  .map((file) => `import "${toImportPath(file, handlerOutputFile)}";`)
  .join("\n")}
`;

await mkdir(path.dirname(outputFile), { recursive: true });
await writeFile(outputFile, content, "utf8");
await writeFile(handlerOutputFile, handlerContent, "utf8");
await recordGenerator(root, {
  id: "scenes",
  command: "npm run codegen:scenes",
  contentInputs: [scriptFile, configFile],
  selections: [
    { kind: "scene", roots: sceneSearchRoots, paths: sceneFiles },
    { kind: "handler", roots: handlerSearchRoots, paths: handlerFiles },
    { kind: "protocol-rpc", roots: serverProtocolSearchRoots, paths: protocolFiles },
    { kind: "protocol-message", roots: serverProtocolSearchRoots, paths: messageProtocolFiles },
  ],
  outputs: [outputFile, handlerOutputFile],
  outputRoots: [
    { path: path.dirname(outputFile), extensions: [".ts"] },
  ],
});
