import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { collectGeneratedFiles, recordGenerator } from "./codegen_manifest.mjs";

const scriptFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptFile), "..");
const configFile = path.join(root, "codegen.config.json");
const config = JSON.parse(await readFile(configFile, "utf8"));
const sdkConfig = config.typescriptClientSdk;

if (!sdkConfig?.enabled) process.exit(0);
if (typeof sdkConfig.sourceRoot !== "string" || !Array.isArray(sdkConfig.outputRoots)) {
  throw new Error("typescriptClientSdk requires sourceRoot and outputRoots");
}

const sourceRoot = path.resolve(root, sdkConfig.sourceRoot);
const distributionExcludes = resolveDistributionExcludes(
  sdkConfig.distributionExcludes ?? [],
);
const outputRoots = sdkConfig.outputRoots.map((value) => {
  if (typeof value !== "string" || !value.trim()) throw new Error("typescriptClientSdk.outputRoots must contain paths");
  return path.resolve(root, value);
});
const fingerprintFile = path.join(sourceRoot, "Generated", "ProtocolFingerprint.ts");
const sourceFiles = (await discoverTypeScript(sourceRoot))
  .filter((file) => file !== fingerprintFile);
const distributableSourceFiles = sourceFiles.filter((file) => !isDistributionExcluded(file));
const protocolFiles = distributableSourceFiles.filter((file) => file.includes(`${path.sep}Generated${path.sep}Model${path.sep}`));
const fingerprint = await hashFiles(protocolFiles);
await mkdir(path.dirname(fingerprintFile), { recursive: true });
await writeFile(
  fingerprintFile,
  `// Generated by tools/codegen_client_sdk.mjs. Do not edit.\nexport const ProtocolFingerprint = "${fingerprint}";\n`,
  "utf8",
);

const completeSourceFiles = [...distributableSourceFiles, fingerprintFile].sort(comparePath);
for (const outputRoot of outputRoots) {
  await removeGeneratedTypeScript(outputRoot);
  for (const excluded of distributionExcludes) {
    await rm(path.join(outputRoot, ...excluded.split("/")), {
      recursive: true,
      force: true,
    });
  }
  for (const sourceFile of completeSourceFiles) {
    const relativePath = path.relative(sourceRoot, sourceFile);
    const outputFile = path.join(outputRoot, relativePath);
    await mkdir(path.dirname(outputFile), { recursive: true });
    await writeFile(outputFile, await readFile(sourceFile));
  }
}

await recordGenerator(root, {
  id: "client-sdk",
  command: "npm run codegen:client-sdk",
  contentInputs: [scriptFile, configFile, ...distributableSourceFiles],
  outputs: [
    fingerprintFile,
    ...await collectGeneratedFiles(outputRoots.map((outputRoot) => ({ path: outputRoot, extensions: [".ts"] }))),
  ],
  outputRoots: outputRoots.map((outputRoot) => ({ path: outputRoot, extensions: [".ts"] })),
});

console.log(`[codegen:client-sdk] generated ${outputRoots.length} SDK copy/copies, fingerprint=${fingerprint.slice(0, 12)}`);

function resolveDistributionExcludes(items) {
  if (!Array.isArray(items)) {
    throw new Error("typescriptClientSdk.distributionExcludes must be an array");
  }
  return items.map((value) => {
    if (typeof value !== "string" || !value.trim()) {
      throw new Error("typescriptClientSdk.distributionExcludes must contain paths");
    }
    return value.replaceAll("\\", "/").replace(/^\.\//, "").replace(/\/$/, "");
  });
}

function isDistributionExcluded(file) {
  const relative = path.relative(sourceRoot, file).replaceAll("\\", "/");
  return distributionExcludes.some((prefix) =>
    relative === prefix || relative.startsWith(`${prefix}/`)
  );
}

async function discoverTypeScript(directory) {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) files.push(...await discoverTypeScript(fullPath));
    else if (entry.isFile() && entry.name.endsWith(".ts")) files.push(fullPath);
  }
  return files.sort(comparePath);
}

async function removeGeneratedTypeScript(directory) {
  let entries;
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch (error) {
    if (error?.code === "ENOENT") return;
    throw error;
  }
  for (const entry of entries) {
    const fullPath = path.join(directory, entry.name);
    if (entry.isDirectory()) await removeGeneratedTypeScript(fullPath);
    else if (entry.isFile() && entry.name.endsWith(".ts")) await rm(fullPath, { force: true });
  }
}

async function hashFiles(files) {
  const hash = createHash("sha256");
  for (const file of files.sort(comparePath)) {
    hash.update(path.relative(sourceRoot, file).replaceAll("\\", "/"));
    hash.update("\0");
    hash.update((await readFile(file, "utf8")).replaceAll("\r\n", "\n"));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function comparePath(left, right) {
  return left.localeCompare(right, "en");
}
