import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { recordGenerator } from "./codegen_manifest.mjs";

const scriptFile = fileURLToPath(import.meta.url);
const root = path.resolve(path.dirname(scriptFile), "..");
const configFile = path.join(root, "codegen.config.json");
const config = JSON.parse(await readFile(configFile, "utf8"));
const godotConfig = config.godotClientSdk;

if (!godotConfig?.enabled) process.exit(0);
if (typeof godotConfig.protocolOutput !== "string" || godotConfig.protocolOutput.length === 0) {
  throw new Error("godotClientSdk.protocolOutput must be a non-empty path");
}

const schemaFile = path.join(root, "proto", "schema.lock.json");
const opcodeFile = path.join(root, "proto", "opcode.lock.json");
const schema = JSON.parse(await readFile(schemaFile, "utf8"));
const opcode = JSON.parse(await readFile(opcodeFile, "utf8"));
const outputFile = path.resolve(root, godotConfig.protocolOutput);
const outputRoot = path.dirname(outputFile);
const entries = schema.entries.filter((entry) => (
  entry.key.startsWith("proto/OuterMessage_C_10001.proto#") ||
  entry.key.startsWith("proto/DataDefine_CS_50001.proto#")
));
const messages = new Map(entries.map((entry) => [entry.name, entry]));
const opcodeByKey = new Map(opcode.entries.map((entry) => [entry.key, entry.code]));
const primitiveTypes = new Set([
  "string",
  "bytes",
  "bool",
  "uint32",
  "int32",
  "sint32",
  "uint64",
  "int64",
  "float",
  "double",
]);

for (const entry of entries) {
  for (const field of entry.fields) {
    if (!primitiveTypes.has(field.type) && !messages.has(field.type)) {
      throw new Error(`Godot codegen cannot resolve field type ${field.type} in ${entry.name}`);
    }
  }
}

const content = emitProtocol(entries, opcodeByKey);
await mkdir(outputRoot, { recursive: true });
await writeFile(outputFile, content, "utf8");
await recordGenerator(root, {
  id: "godot-client-sdk",
  command: "npm run codegen:godot-client-sdk",
  contentInputs: [scriptFile, configFile, schemaFile, opcodeFile],
  outputs: [outputFile],
  outputRoots: [{ path: outputRoot, extensions: [".gd"] }],
});
console.log(`[codegen:godot-client-sdk] generated ${entries.length} message codec(s)`);

function emitProtocol(entries, opcodeByKey) {
  const lines = [
    "# Generated by tools/codegen_godot_client_sdk.mjs. Do not edit by hand.",
    "class_name TiangZProto",
    "extends RefCounted",
    "",
    "## Proto字段编号、消息编号和Codec均由主工程生成；Godot业务只维护连接流程和表现。",
    "## Proto field numbers, message codes, and codecs are generated by the main project; Godot code owns flow and presentation.",
    "",
  ];

  for (const entry of entries.filter((item) => opcodeByKey.has(item.key)).sort(compareEntry)) {
    lines.push(`const ${constantName(entry.name)} := ${opcodeByKey.get(entry.key)}`);
  }
  lines.push("");
  emitRuntimeHelpers(lines);
  for (const entry of entries.sort(compareEntry)) emitCodec(lines, entry, messages);
  return `${lines.join("\n")}\n`;
}

function emitRuntimeHelpers(lines) {
  lines.push(
    "static func frame(msg_code: int, payload: PackedByteArray) -> PackedByteArray:",
    "\tvar result := PackedByteArray()",
    "\tresult.append((msg_code >> 8) & 0xff)",
    "\tresult.append(msg_code & 0xff)",
    "\tresult.append_array(payload)",
    "\treturn result",
    "",
    "static func with_rpc(rpc_id: int, payload: PackedByteArray) -> PackedByteArray:",
    "\tvar result := PackedByteArray()",
    "\tvarint_field(result, 90, rpc_id)",
    "\tresult.append_array(payload)",
    "\treturn result",
    "",
    "static func varint_field(out: PackedByteArray, field: int, value: int, write_zero: bool = false) -> void:",
    "\tif value == 0 and not write_zero:",
    "\t\treturn",
    "\tvarint(out, (field << 3) | 0)",
    "\tvarint(out, value)",
    "",
    "static func sint32_field(out: PackedByteArray, field: int, value: int, write_zero: bool = false) -> void:",
    "\tif value == 0 and not write_zero:",
    "\t\treturn",
    "\tvarint_field(out, field, (value << 1) ^ (value >> 31), true)",
    "",
    "static func int32_field(out: PackedByteArray, field: int, value: int, write_zero: bool = false) -> void:",
    "\tvarint_field(out, field, value, write_zero)",
    "",
    "static func bool_field(out: PackedByteArray, field: int, value: bool, write_false: bool = false) -> void:",
    "\tif not value and not write_false:",
    "\t\treturn",
    "\tvarint_field(out, field, 1 if value else 0, true)",
    "",
    "static func string_field(out: PackedByteArray, field: int, value: String, write_empty: bool = false) -> void:",
    "\tif value.is_empty() and not write_empty:",
    "\t\treturn",
    "\tvar bytes := value.to_utf8_buffer()",
    "\tvarint(out, (field << 3) | 2)",
    "\tvarint(out, bytes.size())",
    "\tout.append_array(bytes)",
    "",
    "static func bytes_field(out: PackedByteArray, field: int, value: PackedByteArray) -> void:",
    "\tvarint(out, (field << 3) | 2)",
    "\tvarint(out, value.size())",
    "\tout.append_array(value)",
    "",
    "static func float_field(out: PackedByteArray, field: int, value: float, write_zero: bool = false) -> void:",
    "\tif is_zero_approx(value) and not write_zero:",
    "\t\treturn",
    "\tvarint(out, (field << 3) | 5)",
    "\tvar buffer := StreamPeerBuffer.new()",
    "\tbuffer.big_endian = false",
    "\tbuffer.put_float(value)",
    "\tout.append_array(buffer.data_array)",
    "",
    "static func double_field(out: PackedByteArray, field: int, value: float, write_zero: bool = false) -> void:",
    "\tif is_zero_approx(value) and not write_zero:",
    "\t\treturn",
    "\tvarint(out, (field << 3) | 1)",
    "\tvar buffer := StreamPeerBuffer.new()",
    "\tbuffer.big_endian = false",
    "\tbuffer.put_double(value)",
    "\tout.append_array(buffer.data_array)",
    "",
    "static func varint(out: PackedByteArray, value: int) -> void:",
    "\tvar current := value",
    "\tif current < 0:",
    "\t\tfor _index in range(9):",
    "\t\t\tout.append(int(current & 0x7f) | 0x80)",
    "\t\t\tcurrent >>= 7",
    "\t\tout.append(int(current) & 0x7f)",
    "\t\treturn",
    "\twhile current >= 0x80:",
    "\t\tout.append(int(current & 0x7f) | 0x80)",
    "\t\tcurrent >>= 7",
    "\tout.append(int(current) & 0xff)",
    "",
    "static func decode_rpc_id(payload: PackedByteArray) -> int:",
    "\tvar reader := TzProtoReader.new(payload)",
    "\twhile not reader.eof():",
    "\t\tvar tag := reader.tag()",
    "\t\tif tag.field == 90 and tag.wire == 0:",
    "\t\t\treturn reader.varint()",
    "\t\treader.skip(tag.wire)",
    "\treturn 0",
    "",
    "static func decode_error(payload: PackedByteArray) -> Dictionary:",
    "\tvar reader := TzProtoReader.new(payload)",
    "\tvar result := {\"rpc_id\": 0, \"error\": 0, \"message\": \"\"}",
    "\twhile not reader.eof():",
    "\t\tvar tag := reader.tag()",
    "\t\tmatch tag.field:",
    "\t\t\t90:",
    "\t\t\t\tresult.rpc_id = reader.varint()",
    "\t\t\t91:",
    "\t\t\t\tresult.error = reader.varint()",
    "\t\t\t92:",
    "\t\t\t\tresult.message = reader.string_value()",
    "\t\t\t_:",
    "\t\t\t\treader.skip(tag.wire)",
    "\treturn result",
    "",
  );
}

function emitCodec(lines, entry, messages) {
  const functionName = snakeCase(entry.name);
  const encoderParameter = entry.fields.some((field) => !field.synthetic) ? "value" : "_value";
  lines.push(`static func encode_${functionName}(${encoderParameter}: Dictionary) -> PackedByteArray:`);
  lines.push("\tvar result := PackedByteArray()");
  for (const field of entry.fields.filter((item) => !item.synthetic)) {
    emitEncoderField(lines, field, messages);
  }
  lines.push("\treturn result", "");
  lines.push(`static func decode_${functionName}(payload: PackedByteArray) -> Dictionary:`);
  lines.push("\tvar reader := TzProtoReader.new(payload)");
  lines.push(`\tvar result := ${dictionaryDefaults(entry.fields)}`);
  lines.push("\twhile not reader.eof():", "\t\tvar tag := reader.tag()", "\t\tmatch tag.field:");
  for (const field of entry.fields) emitDecoderField(lines, field, messages);
  lines.push("\t\t\t_:", "\t\t\t\treader.skip(tag.wire)", "\treturn result", "");
}

function emitEncoderField(lines, field, messages) {
  const key = field.name;
  const number = field.number;
  const type = field.type;
  if (field.repeated) {
    lines.push(`\tfor item in value.get("${key}", []):`);
    if (messages.has(type)) {
      lines.push(`\t\tbytes_field(result, ${number}, encode_${snakeCase(type)}(item))`);
    } else {
      lines.push(`\t\t${encodePrimitive(type, number, "item", true)}`);
    }
    return;
  }
  lines.push(`\tif value.has("${key}"):`);
  if (messages.has(type)) {
    lines.push(`\t\tif value["${key}"] != null:`, `\t\t\tbytes_field(result, ${number}, encode_${snakeCase(type)}(value["${key}"]))`);
  } else {
    lines.push(`\t\t${encodePrimitive(type, number, `value["${key}"]`, false)}`);
  }
}

function encodePrimitive(type, number, expression, repeated) {
  const force = repeated ? ", true" : "";
  switch (type) {
    case "string": return `string_field(result, ${number}, String(${expression})${repeated ? ", true" : ""})`;
    case "bytes": return `bytes_field(result, ${number}, ${expression})`;
    case "bool": return `bool_field(result, ${number}, bool(${expression})${repeated ? ", true" : ""})`;
    case "sint32": return `sint32_field(result, ${number}, int(${expression})${force})`;
    case "int32": return `int32_field(result, ${number}, int(${expression})${force})`;
    case "uint32":
    case "uint64":
    case "int64": return `varint_field(result, ${number}, int(${expression})${force})`;
    case "float": return `float_field(result, ${number}, float(${expression})${force})`;
    case "double": return `double_field(result, ${number}, float(${expression})${force})`;
    default: throw new Error(`unsupported Godot encoder type ${type}`);
  }
}

function emitDecoderField(lines, field, messages) {
  const condition = `tag.wire == ${wireType(field.type, messages)}`;
  const expression = decodeExpression(field.type, messages);
  if (field.repeated) {
    lines.push(`\t\t\t${field.number}:`, `\t\t\t\tif ${condition}:`, `\t\t\t\t\tresult["${field.name}"].append(${expression})`, "\t\t\t\telse:", "\t\t\t\t\treader.skip(tag.wire)");
  } else {
    lines.push(`\t\t\t${field.number}:`, `\t\t\t\tif ${condition}:`, `\t\t\t\t\tresult["${field.name}"] = ${expression}`, "\t\t\t\telse:", "\t\t\t\t\treader.skip(tag.wire)");
  }
}

function decodeExpression(type, messages) {
  if (messages.has(type)) return `decode_${snakeCase(type)}(reader.bytes_value())`;
  switch (type) {
    case "string": return "reader.string_value()";
    case "bytes": return "reader.bytes_value()";
    case "bool": return "reader.boolean()";
    case "uint32": return "reader.uint32()";
    case "int32": return "reader.int32()";
    case "sint32": return "reader.sint32()";
    case "uint64": return "reader.uint64()";
    case "int64": return "reader.int64()";
    case "float": return "reader.float32()";
    case "double": return "reader.float64()";
    default: throw new Error(`unsupported Godot decoder type ${type}`);
  }
}

function wireType(type, messages) {
  if (messages.has(type) || type === "string" || type === "bytes") return 2;
  if (type === "float") return 5;
  if (type === "double") return 1;
  return 0;
}

function dictionaryDefaults(fields) {
  const values = fields.filter((field) => !field.synthetic).map((field) => {
    let value = "0";
    if (field.repeated) value = "[]";
    else if (field.type === "string") value = "\"\"";
    else if (field.type === "bytes") value = "PackedByteArray()";
    else if (field.type === "bool") value = "false";
    else if (field.type === "float" || field.type === "double") value = "0.0";
    else if (field.type && !primitiveTypes.has(field.type)) value = "null";
    return `\"${field.name}\": ${value}`;
  });
  return `{${values.join(", ")}}`;
}

function compareEntry(left, right) {
  return left.name.localeCompare(right.name, "en");
}

function snakeCase(value) {
  const protocolPrefix = /^([A-Za-z]\d[A-Za-z])_(.+)$/.exec(value);
  if (protocolPrefix) {
    return `${protocolPrefix[1].toLowerCase()}_${snakeCaseWords(protocolPrefix[2])}`;
  }
  return snakeCaseWords(value);
}

function snakeCaseWords(value) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();
}

function constantName(value) {
  return snakeCase(value).toUpperCase();
}
