import { mkdir, readFile, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";

export async function generateSystemDeclarations(options) {
  const { root, files, modelRoots, outputRoot: systemDeclarationRoot, publicFile } = options;
  await mkdir(systemDeclarationRoot, { recursive: true });
  const modelGeneration = await collectModelTypes([...modelRoots, ...(options.sharedModelRoots ?? [])]);
  const modelTypes = modelGeneration.types;
  const outputs = [];
  const pending = [];
  const targets = new Set();
  const targetModels = [];

  for (const file of files) {
    const source = ts.createSourceFile(
      file,
      await readFile(file, "utf8"),
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TS,
    );
    for (const declaration of source.statements) {
      if (!ts.isClassDeclaration(declaration)) continue;
      const targetName = systemTargetName(declaration);
      if (!targetName) continue;
      if (!declaration.name) throw new Error(`${relative(file)}: @systemFor class must have a name`);
      if (targets.has(targetName)) throw new Error(`duplicate @systemFor target: ${targetName}`);
      targets.add(targetName);

      const modelMatches = modelTypes.get(targetName) ?? [];
      if (modelMatches.length !== 1) {
        throw new Error(
          `${relative(file)}: @systemFor target ${targetName} resolved to ${modelMatches.length} Model classes`,
        );
      }
      const model = modelMatches[0];
      validateSystemLifecycle(file, source, declaration, model);
      targetModels.push({ name: targetName, file: model.file });
      const output = path.join(systemDeclarationRoot, `${targetName}System.d.ts`);
      const targetModule = toImportPath(model.file, output);
      const modelPublic = toImportPath(publicFile, output);
      const members = systemPublicMembers(file, source, declaration);
      const importLine = modelTypeImports(source, members.join("\n"), modelPublic);
      const content = `// Generated by tools/codegen_module_systems.mjs. Do not edit by hand.\nimport "${targetModule}";\n${importLine}\ndeclare module "${targetModule}" {\n  interface ${targetName} {\n${members.map((member) => `    ${member}`).join("\n")}\n  }\n}\n\nexport {};\n`;
      pending.push({ output, content });
      outputs.push(output);
    }
  }
  for (const matches of modelTypes.values()) {
    if (matches.length !== 1) continue;
    const model = matches[0];
    if (!modelRoots.some(directory => {
      const local = path.relative(directory, model.file);
      return local !== ".." && !local.startsWith(`..${path.sep}`) && !path.isAbsolute(local);
    }) && !targets.has(model.name)) continue;
    const missing = model.transferMethods.filter((method) => !model.methods.has(method));
    if (missing.length > 0 && !targets.has(model.name)) {
      throw new Error(
        `${relative(model.file)}: @transferable requires ${missing.join(" and ")} on Model or its @systemFor class`,
      );
    }
    const asyncTransfer = model.transferMethods.find((method) => model.asyncMethods.has(method));
    if (asyncTransfer) {
      throw new Error(
        `${relative(model.file)}: lifecycle method must be synchronous: ${model.name}.${asyncTransfer}`,
      );
    }
    if (model.lifecycleMethods.length > 0 && !targets.has(model.name)) {
      throw new Error(
        `${relative(model.file)}: @lifecycle requires an @systemFor(${model.name}) class`,
      );
    }
  }
  const expectedOutputs = new Set(outputs.map((file) => path.resolve(file)));
  const obsolete = [];
  for (const entry of await readdir(systemDeclarationRoot, { withFileTypes: true })) {
    const existing = path.join(systemDeclarationRoot, entry.name);
    if (expectedOutputs.has(path.resolve(existing))) continue;
    if (!entry.isFile() || !(await readFile(existing, "utf8")).startsWith("// Generated by tools/codegen_")) {
      throw new Error(`refusing to prune non-generated system declaration: ${existing}`);
    }
    obsolete.push(existing);
  }
  for (const { output, content } of pending) {
    const previous = await readFile(output, "utf8").catch(error => { if (error.code !== "ENOENT") throw error; });
    if (previous !== undefined && !previous.startsWith("// Generated by tools/codegen_")) throw new Error(`refusing to overwrite handwritten system declaration: ${output}`);
    if (options.check && previous !== content) throw new Error(`stale system declaration: ${output}`);
  }
  if (options.check && obsolete.length) throw new Error(`obsolete system declaration: ${obsolete[0]}`);
  if (!options.check) {
    for (const { output, content } of pending) await writeFile(output, content, "utf8");
    for (const existing of obsolete) await rm(existing);
  }
  return {
    outputs: outputs.sort((left, right) => left.localeCompare(right)),
    targets: targetModels.sort((left, right) => left.name.localeCompare(right.name)),
    modelFiles: modelGeneration.files,
  };

  function relative(file) { return path.relative(root, file).replaceAll(path.sep, "/"); }
}

async function collectModelTypes(modelRoots) {
  const files = await collectFiles(
    modelRoots,
    (file) => file.endsWith(".ts"),
  );
  const result = new Map();
  for (const file of files) {
    const source = ts.createSourceFile(
      file,
      await readFile(file, "utf8"),
      ts.ScriptTarget.Latest,
      true,
      ts.ScriptKind.TS,
    );
    for (const declaration of source.statements) {
      if (!ts.isClassDeclaration(declaration) || !declaration.name) continue;
      const matches = result.get(declaration.name.text) ?? [];
      const methods = new Set();
      const asyncMethods = new Set();
      for (const member of declaration.members) {
        if (!ts.isMethodDeclaration(member) || !member.name) continue;
        const name = member.name.getText(source);
        methods.add(name);
        if (hasModifier(member, ts.SyntaxKind.AsyncKeyword)) asyncMethods.add(name);
      }
      matches.push({
        name: declaration.name.text,
        file,
        methods,
        asyncMethods,
        lifecycleMethods: modelLifecycleMethods(file, source, declaration),
        transferMethods: hasDecorator(declaration, "transferable")
          ? ["CaptureTransfer", "RestoreTransfer"]
          : [],
      });
      result.set(declaration.name.text, matches);
    }
  }
  return { types: result, files };
}

function modelLifecycleMethods(file, source, declaration) {
  const decorator = (ts.getDecorators(declaration) ?? []).find((item) =>
    ts.isCallExpression(item.expression) &&
    ts.isIdentifier(item.expression.expression) &&
    item.expression.expression.text === "lifecycle"
  );
  if (!decorator) return [];
  const call = decorator.expression;
  if (call.arguments.length !== 1 || !ts.isObjectLiteralExpression(call.arguments[0])) {
    throw new Error(`${relative(file)}: @lifecycle requires one object literal`);
  }
  const names = new Map([
    ["awake", "Awake"],
    ["destroy", "OnDestroy"],
    ["deserialize", "Deserialize"],
  ]);
  const result = [];
  for (const property of call.arguments[0].properties) {
    if (!ts.isPropertyAssignment(property) || !ts.isIdentifier(property.name)) {
      throw new Error(`${relative(file)}: @lifecycle only accepts named boolean properties`);
    }
    const method = names.get(property.name.text);
    if (!method) {
      throw new Error(`${relative(file)}: unknown @lifecycle option ${property.name.text}`);
    }
    if (property.initializer.kind !== ts.SyntaxKind.TrueKeyword) {
      throw new Error(`${relative(file)}: @lifecycle.${property.name.text} must be true or omitted`);
    }
    result.push(method);
  }
  if (result.length === 0) throw new Error(`${relative(file)}: @lifecycle declaration is empty`);
  return result;
}

function hasDecorator(declaration, name) {
  return (ts.getDecorators(declaration) ?? []).some((decorator) =>
    ts.isCallExpression(decorator.expression) &&
    ts.isIdentifier(decorator.expression.expression) &&
    decorator.expression.expression.text === name
  );
}

function validateSystemLifecycle(file, source, declaration, model) {
  const methods = new Map();
  for (const member of declaration.members) {
    if (!ts.isMethodDeclaration(member) || !member.name) continue;
    methods.set(member.name.getText(source), member);
  }
  const required = [
    ...model.lifecycleMethods,
    ...model.transferMethods.filter((method) => !model.methods.has(method)),
  ];
  for (const method of required) {
    const declaration = methods.get(method);
    if (!declaration) {
      throw new Error(`${relative(file)}: ${model.name} requires lifecycle method ${method}`);
    }
    if (hasModifier(declaration, ts.SyntaxKind.AsyncKeyword)) {
      throw new Error(`${relative(file)}: lifecycle method must be synchronous: ${model.name}.${method}`);
    }
  }
}

function systemTargetName(declaration) {
  for (const decorator of ts.getDecorators(declaration) ?? []) {
    if (!ts.isCallExpression(decorator.expression)) continue;
    const call = decorator.expression;
    if (!ts.isIdentifier(call.expression) || call.expression.text !== "systemFor") continue;
    if (call.arguments.length !== 1 || !ts.isIdentifier(call.arguments[0])) {
      throw new Error("@systemFor requires one Model class identifier");
    }
    return call.arguments[0].text;
  }
  return undefined;
}

function systemPublicMembers(file, source, declaration) {
  const result = [];
  const accessors = new Map();
  for (const member of declaration.members) {
    if (hasModifier(member, ts.SyntaxKind.PrivateKeyword) || hasModifier(member, ts.SyntaxKind.ProtectedKeyword)) {
      continue;
    }
    if (ts.isMethodDeclaration(member)) {
      if (!member.name || !member.type) {
        throw new Error(`${relative(file)}: public System methods require explicit return types`);
      }
      const typeParameters = member.typeParameters?.map((item) => item.getText(source)).join(", ");
      const parameters = member.parameters.map((parameter) => parameterSignature(file, source, parameter));
      result.push(
        `${member.name.getText(source)}${typeParameters ? `<${typeParameters}>` : ""}(${parameters.join(", ")}): ${member.type.getText(source)};`,
      );
      continue;
    }
    if (ts.isGetAccessorDeclaration(member) || ts.isSetAccessorDeclaration(member)) {
      const name = member.name.getText(source);
      const current = accessors.get(name) ?? {};
      if (ts.isGetAccessorDeclaration(member)) {
        if (!member.type) throw new Error(`${relative(file)}: public System getters require an explicit type`);
        current.get = member.type.getText(source);
      } else {
        const parameter = member.parameters[0];
        if (!parameter?.type) throw new Error(`${relative(file)}: public System setters require an explicit type`);
        current.set = parameter.type.getText(source);
      }
      accessors.set(name, current);
    }
  }
  for (const [name, accessor] of accessors) {
    if (accessor.get && accessor.set && accessor.get !== accessor.set) {
      throw new Error(`${relative(file)}: System accessor type mismatch: ${name}`);
    }
    result.push(`${accessor.set ? "" : "readonly "}${name}: ${accessor.set ?? accessor.get};`);
  }
  return result;
}

function parameterSignature(file, source, parameter) {
  if (!parameter.type) throw new Error(`${relative(file)}: public System parameters require explicit types`);
  const optional = parameter.questionToken || parameter.initializer ? "?" : "";
  const rest = parameter.dotDotDotToken ? "..." : "";
  return `${rest}${parameter.name.getText(source)}${optional}: ${parameter.type.getText(source)}`;
}

function modelTypeImports(source, publicSignatures, modelPublic) {
  const groups = new Map();
  for (const statement of source.statements) {
    if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier)) continue;
    const specifier = statement.moduleSpecifier.text;
    if (!specifier.startsWith("#tiangz/")) continue;
    const bindings = statement.importClause?.namedBindings;
    if (!bindings || !ts.isNamedImports(bindings)) continue;
    for (const element of bindings.elements) {
      if (!new RegExp(`\\b${escapeRegExp(element.name.text)}\\b`).test(publicSignatures)) continue;
      const target = specifier === "#tiangz/module" ? modelPublic : specifier;
      if (!groups.has(target)) groups.set(target, new Set());
      groups.get(target).add(element.propertyName ? `${element.propertyName.text} as ${element.name.text}` : element.name.text);
    }
  }
  return [...groups].map(([specifier, names]) => `import type { ${[...names].sort().join(", ")} } from ${JSON.stringify(specifier)};\n`).join("");
}

function escapeRegExp(value) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function hasModifier(node, kind) {
  return node.modifiers?.some((modifier) => modifier.kind === kind) ?? false;
}

function relative(file) {
  return file.replaceAll(path.sep, "/");
}

function toImportPath(file, output) {
  const relative = path.relative(path.dirname(output), file).replaceAll(path.sep, "/").replace(/\.ts$/, "");
  return relative.startsWith(".") ? relative : `./${relative}`;
}

export async function collectFiles(roots, predicate = file => file.endsWith(".ts")) {
  const files = [];
  for (const root of roots) {
    for (const entry of await readdir(root, { withFileTypes: true })) {
      const file = path.join(root, entry.name);
      if (entry.isSymbolicLink()) throw new Error(`source links are forbidden: ${file}`);
      if (entry.isDirectory() && !["generated", "dist", "node_modules"].includes(entry.name)) files.push(...await collectFiles([file], predicate));
      else if (entry.isFile() && predicate(file)) files.push(file);
    }
  }
  return [...new Set(files)].sort();
}
