import assert from "node:assert/strict";
import { test } from "node:test";
import { mkdtemp, mkdir, readFile, writeFile, rm } from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { generateSystemDeclarations } from "./system_declarations.mjs";

test("external Systems get declarations without requiring unrelated shared domain systems", async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), "tiangz-systems-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const model = path.join(root, "model"), shared = path.join(root, "shared"), outputRoot = path.join(root, "generated");
  await mkdir(model); await mkdir(shared);
  await writeFile(path.join(model, "Counter.ts"), "export class Counter { protected count = 0; }\n");
  await writeFile(path.join(shared, "Unrelated.ts"), "@lifecycle({ awake: true }) export class Unrelated {}\n");
  const system = path.join(root, "CounterSystem.ts");
  await writeFile(system, 'import { Counter } from "#tiangz/module";\n@systemFor(Counter) export class CounterSystem extends Counter { Increment(amount: number): number { return this.count += amount; } }\n');
  const options = { root, files: [system], modelRoots: [model], sharedModelRoots: [shared], outputRoot, publicFile: path.join(model, "Counter.ts") };
  const result = await generateSystemDeclarations(options);
  assert.deepEqual(result.targets.map(t => t.name), ["Counter"]);
  const file = path.join(outputRoot, "CounterSystem.d.ts");
  assert.match(await readFile(file, "utf8"), /Increment\(amount: number\): number/);
  await generateSystemDeclarations({ ...options, check: true });
  await writeFile(file, "// handwritten\n");
  await assert.rejects(generateSystemDeclarations(options), /handwritten/);
  assert.equal(await readFile(file, "utf8"), "// handwritten\n");
});

test("lifecycle validation preserves declarations on failure and prunes only generated obsolete outputs", async t => {
  const root = await mkdtemp(path.join(os.tmpdir(), "tiangz-lifecycle-systems-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const model = path.join(root, "model"), outputRoot = path.join(root, "generated");
  await mkdir(model); await mkdir(outputRoot);
  await writeFile(path.join(model, "Counter.ts"), "@transferable() @lifecycle({ awake: true, destroy: true, deserialize: true }) export class Counter {}\n");
  const system = path.join(root, "CounterSystem.ts");
  const options = { root, files: [system], modelRoots: [model], outputRoot, publicFile: path.join(model, "Counter.ts") };
  const sentinel = path.join(outputRoot, "OldSystem.d.ts");
  const original = "// Generated by tools/codegen_module_systems.mjs. Do not edit by hand.\n";
  await writeFile(sentinel, original);
  await writeFile(system, "@systemFor(Counter) export class CounterSystem extends Counter { protected Awake(): void {} }\n");
  await assert.rejects(generateSystemDeclarations(options), /requires lifecycle method OnDestroy/);
  assert.equal(await readFile(sentinel, "utf8"), original);
  await writeFile(system, "@systemFor(Counter) export class CounterSystem extends Counter { protected Awake(): void {} protected OnDestroy(): void {} Deserialize(): void {} CaptureTransfer(): number {return 1;} RestoreTransfer(state: number): void {} }\n");
  await generateSystemDeclarations(options);
  await assert.rejects(readFile(sentinel), { code: "ENOENT" });
  const active = await readFile(path.join(outputRoot, "CounterSystem.d.ts"), "utf8");
  await writeFile(system, (await readFile(system, "utf8")).replace("Deserialize(): void {}", "async Deserialize(): Promise<void> {}"));
  await assert.rejects(generateSystemDeclarations(options), /synchronous|async/);
  assert.equal(await readFile(path.join(outputRoot, "CounterSystem.d.ts"), "utf8"), active);
});
